README.md

- Improve spelling of the programming language names
- Improve consistency by changing the `Cspell` name to `cspell` in the beginning.
- Add Markdown syntax to show the name as a runnable command.

docs(README.md) improve spelling

---

dictionaries/miscTerms.txt

adding "unshare" as the opposite of "share" action

add "unshare" to the misc terms

---

dictionaries/html.txt
dictionaries/miscTerms.txt
dictionaries/npm.txt

Extra terms for `html`, `miscTerms` and `npm` dictionaries

add extra terms for various dictionaries

---

dictionaries/css.txt

https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes

Add "keyframes" to the CSS terms

---

dictionaries/softwareTerms.txt

https://en.wikipedia.org/wiki/Iteratee
https://en.wikipedia.org/wiki/Iteratee#Enumeratees

+ `enumeratee` `iteratee` to softwareTerms.txt

---

dictionaries/softwareTerms.txt

Part of https://github.com/Jason-Rev/vscode-spell-checker/issues/258

Add some terms

---

dictionaries/fonts.txt

https://en.wikipedia.org/wiki/Segoe

Add Segoe font

---

packages/cspell/dictionaries/csharp.txt

https://docs.microsoft.com/en-ca/dotnet/csharp/language-reference/keywords/nameof

csharp: Add "nameof" operator

---

.vscode/settings.json
cspell.schema.json
package-lock.json
package.json
packages/cspell-lib/.vscode/settings.json
packages/cspell-lib/package.json
packages/cspell-lib/src/Settings/CSpellSettingsDef.ts
packages/cspell/.vscode/settings.json

Move cspell.schema.json to root and add tests

---

.gitattributes
azure-pipelines.yml
cspell.json

Fix build issues on Azure

---

packages/cspell-trie-lib/src/lib/consolidate.test.ts
packages/cspell-trie-lib/src/lib/consolidate.ts
packages/cspell-trie-lib/src/lib/importExport.ts
packages/cspell-trie-lib/src/lib/importExportV3.test.ts
packages/cspell-trie-lib/src/lib/importExportV3.ts

Convert a TrieNode into a DAWG

---

packages/cspell-util-bundle/package.json

use rimraf instead of rm

---

packages/cspell-glob/package.json
packages/cspell-io/package.json
packages/cspell-lib/package.json
packages/cspell-tools/package.json
packages/cspell-trie-lib/package.json
packages/cspell-trie/package.json
packages/cspell-trie2-lib/package.json
packages/cspell-util-bundle/package.json
packages/cspell/package.json

update test-watch script

---

packages/cspell-glob/src/GlobMatcher.test.ts
packages/cspell-glob/src/GlobMatcher.ts
packages/cspell/src/application.ts

cspell-glob did NOT correctly support Windows.
This should fix: #171 #173 #135

[cspell-glob] Support Windows

---

package-lock.json
package.json

Add codecov support

---

cspell.schema.json
packages/cspell-lib/package.json
packages/cspell-lib/src/Settings/CSpellSettingsDef.ts
packages/cspell-lib/src/Settings/DictionarySettings.test.ts
packages/cspell-lib/src/Settings/DictionarySettings.ts
packages/cspell-lib/src/Settings/LanguageSettings.ts

Partial fix of locale spelling error.

fix: Expose allowed DictionaryDefinitionAlternate

---

package-lock.json
package.json
packages/cspell-lib/package-lock.json
packages/cspell-lib/src/util/text.ts
packages/cspell-util-bundle/package-lock.json
packages/cspell-util-bundle/package.json

fix: fix missing xregexp types

---

packages/cspell-lib/package-lock.json
packages/cspell-lib/package.json

Ensure that minimatch is part of cspell-lib

---

.gitignore
packages/cspell-lib/src/SpellingDictionary/Dictionaries.test.ts
packages/cspell-lib/src/SpellingDictionary/Dictionaries.ts
packages/cspell-lib/src/SpellingDictionary/DictionaryLoader.ts
packages/cspell-lib/src/index.test.ts
packages/cspell-lib/src/index.ts
packages/cspell-lib/src/util/fileReader.ts

Make sure `clearCachedSettings` will cause dictionaries to be re-loaded if they have changed.

fix: make sure dictionaries are re-loaded if they have changed.

---

packages/cspell-lib/dictionaries/html.txt
packages/cspell-lib/dictionaries/miscTerms.txt

various missing terms for `misc` and `html` dictionaries

add additional terms (misc, html)

---

.github/workflows/codeql-analysis.yml

Found 2 minor things that might actually be false positives https://github.com/nschonni/cspell/security/code-scanning?query=tool%3ACodeQL+is%3Aopen+ref%3Arefs%2Fpull%2F1%2Fmerge

chore: Add CodeQL GitHub Action

---

update-packages.sh

Looks like you've moved this to a npm script task now

chore: Remove update-package.sh

---

packages/cspell-trie-lib/src/lib/suggest.ts

* fix code QL warning
* Update packages/cspell-trie-lib/src/lib/suggest.ts
Co-authored-by: Nick Schonning <nschonni@gmail.com>

fix: code QL warning (#404)

---

packages/cspell-lib/src/LanguageIds.ts

- Common web fonts
- Icon files used by favorites

fix: Add common web binaries extensions

---

.github/workflows/integration-test.yml

ci: Create integration-test.yml

---

.editorconfig

Match .gitattributes and special test file patterns

chore: EditorConfig end of line config

---

.github/workflows/lint.yml

Not pinning a particular version, just looking for inline commenting

chore: Add setup-node for problem matcher

---

packages/cspell-lib/src/Settings/CSpellSettingsDef.ts
packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
packages/cspell-lib/src/Settings/DefaultSettings.ts

Fix: [Server problem with version 1.9.3 · Issue #577 · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/issues/577)

fix: Issue with crash on missing files.

---

package-lock.json
package.json

Only used by cspell-util-bundle

chore: Remove webpack from root

---

packages/cspell/src/app.test.ts
packages/cspell/src/app.ts

The error code should be set if:
`check` fails to find files or has errors
`trace` fails to find a word in any dictionary

fix: make sure the error code is correctly set

---

packages/cspell/src/app.ts
packages/cspell/src/application.test.ts
packages/cspell/src/application.ts
packages/cspell/src/index.ts

Make sure emitter types are correctly exposed.

fix: Expose Emitter types

---

packages/cspell-trie-lib/src/lib/suggest-en.test.ts
packages/cspell-trie-lib/src/lib/suggest.ts

fix: Improve suggestions for short words

---

.prettierignore
packages/cspell-lib/src/util/__snapshots__/text.test.ts.snap
packages/cspell-lib/src/util/search.test.ts
packages/cspell-lib/src/util/search.ts
packages/cspell-lib/src/util/text.test.ts
packages/cspell-lib/src/util/text.ts
packages/cspell/src/__snapshots__/app.test.ts.snap
packages/cspell/src/app.ts
packages/cspell/src/application.ts
packages/cspell/src/emitters.ts

- `--relative` - files names are relative to the current working dir
- `--show-context` - shows the text surrounding the an issue.

feat: Add options --show-context and --relative

---

packages/cspell-lib/src/__snapshots__/validator.test.ts.snap
packages/cspell-lib/src/util/text.ts
packages/cspell-lib/src/validator.test.ts
packages/cspell-lib/src/validator.ts
packages/cspell/src/__snapshots__/app.test.ts.snap
packages/cspell/src/app.ts
packages/cspell/src/application.ts
packages/cspell/src/emitters.ts

feat: support displaying suggestions

---

packages/cspell-lib/src/util/wordSplitter.ts
packages/cspell/bin.js
packages/cspell/src/app.ts

fix: make sure version and help do not exit with non-zero code.

---

packages/cspell-lib/cspell.config.json
packages/cspell-lib/samples/linked/cspell.circularA.json
packages/cspell-lib/samples/linked/cspell.circularB.json
packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
packages/cspell-types/src/settings/CSpellSettingsDef.ts

- Add an optional source field to the glob definition.
- Handle circular imports.

fix: be able to report on glob source.

---

cspell-dict.txt
packages/cspell-glob/.vscode/launch.json
packages/cspell-glob/src/GlobMatcher.test.ts
packages/cspell-glob/src/GlobMatcher.ts
packages/cspell-glob/src/globHelper.test.ts
packages/cspell-glob/src/globHelper.ts
packages/cspell/cSpell.json
packages/cspell/src/lint.ts
packages/cspell/src/util/glob.test.ts
packages/cspell/src/util/glob.ts

Fix an issue if the drive letter case does not match on windows.

fix: make sure glob patterns match on windows

---

packages/cspell/samples/latex/cspell.json
packages/cspell/samples/latex/ebook/ebook.tex
packages/cspell/samples/latex/latex.tex
packages/cspell/src/lint.test.ts
packages/cspell/src/lint.ts

fix: file globs listed on the command line override files in the config.

---

.github/ISSUE_TEMPLATE/config.yml

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser

chore: Point to cspell-dicts issues for typos

---

packages/cspell-lib/src/util/text.test.ts
packages/cspell-lib/src/util/textRegex.ts
packages/cspell-lib/src/util/wordSplitter.test.ts
packages/cspell-lib/src/util/wordSplitter.ts

fix: Correctly handle leading and trailing single quote

---

.github/workflows/cspell-action.yml
package.json
packages/Samples/package.json
packages/Samples/tests/exclude_dictionary/cspell.json
packages/Samples/tests/exclude_dictionary/test.md
packages/cspell-lib/src/Settings/DictionarySettings.test.ts
packages/cspell-lib/src/Settings/DictionarySettings.ts
packages/cspell/README.md

fix: correct how dictionaries are disabled

---

integration-tests/config/config.json
integration-tests/package.json
integration-tests/snapshots/AdaDoom3/AdaDoom3/snapshot.txt
integration-tests/snapshots/Azure/azure-rest-api-specs/snapshot.txt
integration-tests/snapshots/MartinThoma/LaTeX-examples/snapshot.txt
integration-tests/snapshots/TheAlgorithms/Python/snapshot.txt
integration-tests/snapshots/alexiosc/megistos/snapshot.txt
integration-tests/snapshots/django/django/snapshot.txt
integration-tests/snapshots/googleapis/google-cloud-cpp/snapshot.txt
integration-tests/snapshots/graphql/graphql-js/snapshot.txt
integration-tests/snapshots/graphql/graphql-spec/snapshot.txt
integration-tests/snapshots/liriliri/licia/snapshot.txt
integration-tests/snapshots/mdx-js/mdx/snapshot.txt
integration-tests/snapshots/microsoft/TypeScript-Website/snapshot.txt
integration-tests/snapshots/php/php-src/snapshot.txt
integration-tests/snapshots/pycontribs/jira/snapshot.txt
integration-tests/snapshots/typescript-cheatsheets/react/snapshot.txt
integration-tests/snapshots/typescript-eslint/typescript-eslint/snapshot.txt
packages/cspell-lib/package-lock.json
packages/cspell-lib/package.json
packages/cspell-lib/samples/.cspell.json
packages/cspell-lib/samples/French.md
packages/cspell-lib/samples/words.txt
packages/cspell-lib/src/test/french.spec.ts
packages/cspell-lib/src/util/textRegex.ts
packages/cspell-lib/src/util/wordSplitter.test.ts
packages/cspell-lib/src/util/wordSplitter.ts

Allow for natural word breaks on `'`

fix: #1336

---

packages/cspell-lib/src/SpellingDictionary/Dictionaries.test.ts
packages/cspell-lib/src/SpellingDictionary/Dictionaries.ts
packages/cspell-lib/src/SpellingDictionary/SpellingDictionary.ts
packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryCollection.test.ts
packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryCollection.ts
packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryFromTrie.ts
packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryMethods.test.ts
packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryMethods.ts
packages/cspell-lib/src/SpellingDictionary/createSpellingDictionary.test.ts
packages/cspell-lib/src/SpellingDictionary/createSpellingDictionary.ts
packages/cspell-lib/src/trace.test.ts
packages/cspell-lib/src/trace.ts
packages/cspell-lib/src/util/util.ts
packages/cspell-trie-lib/src/lib/trie.ts
packages/cspell/src/__snapshots__/app.test.ts.snap
packages/cspell/src/app.ts
packages/cspell/src/application.ts
packages/cspell/src/traceEmitter.ts

Display more information about the word that was found.

feat: Improve `trace` words command results.

---

docs/configuration/index.md
packages/cspell/README.md

fix: Fix version number reference

---

packages/cspell-lib/package-lock.json
packages/cspell-lib/package.json

Reverts streetsidesoftware/cspell#1650

Revert "build(deps): bump @cspell/dict-en-gb from 1.1.33 to 2.0.1"

---

package.json

This greatly speeds up eslint for files which were not modified.

enable eslint cache

---

.github/workflows/test.yml

This reverts commit 0d3091f7a8b3f863b34c5fcbb21cc3cd2c8f08b9.

Revert "test: fix github-actions (#1665)"

---

packages/cspell-trie-lib/src/lib/timer.test.ts
packages/cspell-trie-lib/src/lib/timer.ts

Have a backup timer

---

packages/cspell-trie-lib/src/lib/timer.test.ts
packages/cspell-trie-lib/src/lib/timer.ts

fix: Use process directly instead of importing it.

---

packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
test-fixtures/issues/issue-1729/a.yaml
test-fixtures/issues/issue-1729/b.yaml

fix: Allow config file version to be a number.

---

.github/workflows/coverage.yml

ci: CSpell4 - Disable Coveralls 

---

.github/workflows/integration-test.yml

Only run an integration test if something has changed.

ci: Try caching integration test runs to avoid repeat runs.

---

integration-tests/snapshots/MartinThoma/LaTeX-examples/snapshot.txt
integration-tests/snapshots/django/django/snapshot.txt
integration-tests/snapshots/mdx-js/mdx/snapshot.txt
packages/cspell-trie-lib/src/lib/suggest-en-a-star.test.ts
packages/cspell/src/cli-reporter.test.ts
packages/cspell/src/cli-reporter.ts

- Use a substitution function to ensure Issue formatting is correct.

fix: Ensure cli-reporter displays the correct message.

---

integration-tests/snapshots/AdaDoom3/AdaDoom3/report.yaml
integration-tests/snapshots/AdaDoom3/AdaDoom3/snapshot.txt
integration-tests/snapshots/Azure/azure-rest-api-specs/snapshot.txt
integration-tests/snapshots/SoftwareBrothers/admin-bro/snapshot.txt
integration-tests/snapshots/TheAlgorithms/Python/report.yaml
integration-tests/snapshots/TheAlgorithms/Python/snapshot.txt
integration-tests/snapshots/django/django/report.yaml
integration-tests/snapshots/django/django/snapshot.txt
integration-tests/snapshots/liriliri/licia/snapshot.txt
integration-tests/snapshots/microsoft/TypeScript-Website/report.yaml
integration-tests/snapshots/microsoft/TypeScript-Website/snapshot.txt
integration-tests/snapshots/php/php-src/report.yaml
integration-tests/snapshots/php/php-src/snapshot.txt
integration-tests/snapshots/prettier/prettier/snapshot.txt
integration-tests/snapshots/pycontribs/jira/report.yaml
integration-tests/snapshots/pycontribs/jira/snapshot.txt
packages/cspell-types/src/CSpellReporter.ts
packages/cspell/src/cli-reporter.ts
packages/cspell/src/fileHelper.ts
packages/cspell/src/lint.ts
packages/cspell/src/util/cache/DiskCache.test.ts
packages/cspell/src/util/cache/DiskCache.ts

Make sure files are counted, even if they are cached.

fix: fix #1807

---

packages/cspell-lib/src/Settings/InDocSettings.test.ts
packages/cspell-lib/src/Settings/InDocSettings.ts
packages/cspell-lib/src/Settings/LanguageSettings.test.ts
packages/cspell-lib/src/Settings/LanguageSettings.ts

fix: In Document settings.

---

packages/cspell-lib/src/Settings/InDocSettings.test.ts
packages/cspell-lib/src/Settings/InDocSettings.ts
packages/cspell-trie-lib/package-lock.json
packages/cspell-trie-lib/package.json
packages/cspell-trie-lib/src/lib/suggest-es.test.ts

Support `enableCaseSensitive`/`disableCaseSensitive` in document settings.

fix: Add `enableCaseSensitive`/`disableCaseSensitive`

---

cspell.schema.json
packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
packages/cspell-trie-lib/src/lib/util.ts
packages/cspell-types/cspell.schema.json
packages/cspell-types/package-lock.json
packages/cspell-types/package.json
packages/cspell-types/src/CSpellSettingsDef.ts

The JSON schema will now include the `deprecated` flag.

fix: Update schema generator

---

packages/cspell-lib/samples/forbid-words/README.md
packages/cspell-lib/samples/forbid-words/cspell.json
packages/cspell-lib/src/textValidator.test.ts
packages/cspell-lib/src/textValidator.ts

dev: Catch forbidden whole words

---

packages/cspell-glob/src/GlobMatcher.ts
packages/cspell-glob/src/GlobMatcherTypes.ts
packages/cspell-glob/src/globHelper.ts
packages/cspell-grammar/tsconfig.json
packages/cspell-lib/tsconfig.json
packages/cspell-tools/tsconfig.json
packages/cspell-trie-lib/tsconfig.json
packages/cspell-types/src/CSpellSettingsDef.ts
packages/cspell/tsconfig.json
packages/hunspell-reader/tsconfig.json
tsconfig.json

Turn on `exactOptionalPropertyTypes` for types.

fix: fix #2011

---

.github/workflows/coverage.yml
.github/workflows/cspell-action.yml
.github/workflows/cspell-cli.yml
.github/workflows/lint-docs.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.github/workflows/update-dependencies-cspell4.yml
.github/workflows/update-dependencies.yml

It was already setup for some of the jobs, this extends it to the rest

chore: add setup-node caching to remaining jobs

---

packages/cspell-lib/src/util/resolveFile.test.ts

Inlined the code since it couldn't understand the double redirection

fix: jest/expect-expect warning

---

packages/cspell-lib/src/LanguageIds.ts

- [The Dhall configuration language](https://dhall-lang.org/#)
- [PureScript](https://www.purescript.org/)

fix: make cspell aware of PureScript and Dhall

---

.eslintrc.js
integration-tests/src/check.ts
package-lock.json
package.json

Add it back when [Support ESLint 8.x · Issue #218 · xjamundx/eslint-plugin-promise](https://github.com/xjamundx/eslint-plugin-promise/issues/218) is resolved.

ci: Remove eslint-plugin-promise

---

packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
packages/cspell-lib/src/Settings/DictionarySettings.ts
packages/cspell-lib/src/Settings/index.ts
packages/cspell-lib/src/SpellingDictionary/Dictionaries.test.ts
packages/cspell-lib/src/SpellingDictionary/Dictionaries.ts
packages/cspell/.vscode/launch.json
packages/cspell/cSpell.json
packages/cspell/src/lint/lint.ts
packages/cspell/src/util/cache/CSpellLintResultCache.ts
packages/cspell/src/util/cache/DiskCache.test.ts
packages/cspell/src/util/cache/DiskCache.ts

fix: Invalidate cache when config has changed

---

.github/workflows/cspell-action.yml

chore: Update cspell-action

---

integration-tests/config/config.json
integration-tests/snapshots/apollographql/apollo-server/snapshot.txt
integration-tests/snapshots/shoelace-style/shoelace/snapshot.txt
integration-tests/src/config.ts

- add shoelace
- update apollo

ci: for integration tests, make `**` the default

---

lerna.json
rfc/rfc-0001 suggestions/README.md
rfc/rfc-0001 suggestions/jest.config.js
rfc/rfc-0001 suggestions/package-lock.json
rfc/rfc-0001 suggestions/package.json
rfc/rfc-0001 suggestions/src/config-definitions.ts
rfc/rfc-0001 suggestions/tsconfig.json

[Discuss ways to define suggestions · Discussion #2246](https://github.com/streetsidesoftware/cspell/discussions/2246)

doc: RFC Proposal for Suggestion Lists

---

cspell-dict.txt
cspell.json

ci: forbid `therefor`

---

cspell-ignore-words.txt
cspell.json
packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts
packages/cspell-lib/src/suggestions.ts
packages/cspell-lib/src/trace.ts
packages/cspell/src/__snapshots__/app.test.ts.snap
packages/cspell/src/commandSuggestion.ts
packages/cspell/src/emitters/__snapshots__/suggestionsEmitter.test.ts.snap
packages/cspell/src/emitters/suggestionsEmitter.test.ts
packages/cspell/src/emitters/suggestionsEmitter.ts

- When making suggestions mark forbidden and no suggest words

fix: (cspell) Mark forbidden and no suggest words

---

cspell.schema.json
packages/cspell-lib/src/__snapshots__/index.test.ts.snap
packages/cspell-types/cspell.schema.json
packages/cspell-types/src/CSpellSettingsDef.ts
packages/cspell-types/src/configFields.ts
packages/cspell/samples/fail-fast/cspell.json
packages/cspell/samples/fail-fast/fail-fast-cspell.json
packages/cspell/samples/fail-fast/first-fail.txt
packages/cspell/samples/fail-fast/second-fail.txt
packages/cspell/src/lint/lint.test.ts
packages/cspell/src/lint/lint.ts

Closes #2294
This is my first contribution, not sure if I placed this config option in the right place, and also not sure if that's the most optimal way to test this, but I guess it works. Any feedback is appreciated.

feat: Add `failFast` config option to exit as soon as an issue encountered

---

packages/cspell-trie-lib/src/lib/TrieNode.ts
packages/cspell-trie-lib/src/lib/find.ts
packages/cspell-trie-lib/src/lib/trie-util.ts
packages/cspell-trie-lib/src/lib/types.ts

fix: Explicitly import `types`

---

tsconfig.json

fix: Update tsconfig.json

---

packages/cspell-lib/src/SpellingDictionary/createSpellingDictionary.test.ts
packages/cspell-trie-lib/src/lib/mappers/__snapshots__/mapDictionaryInfo.test.ts.snap
packages/cspell-trie-lib/src/lib/mappers/__snapshots__/mapHunspellInformation.test.ts.snap
packages/cspell-trie-lib/src/lib/mappers/mapHunspellInformation.test.ts
packages/cspell-trie-lib/src/lib/mappers/mapToSuggestionCostDef.ts
packages/cspell-trie-lib/src/lib/suggestions/genSuggestionsOptions.ts
packages/cspell-trie-lib/src/lib/suggestions/suggest-en-a-star.test.ts
packages/cspell-trie-lib/src/lib/suggestions/suggest-en.test.ts
packages/cspell-trie-lib/src/lib/suggestions/suggest.test.ts
packages/cspell-trie-lib/src/lib/suggestions/suggest.ts
packages/cspell-trie-lib/src/lib/suggestions/suggestAStar.test.ts
packages/cspell-trie-lib/src/lib/suggestions/suggestAStar.ts
packages/cspell-trie-lib/src/lib/suggestions/suggestCollector.test.ts
packages/cspell-trie-lib/src/lib/trie.test.ts
packages/cspell-trie-lib/src/lib/trie.ts
packages/cspell-trie-lib/src/lib/walker/hintedWalker.test.ts
packages/cspell-trie-lib/src/lib/walker/hintedWalker.ts
packages/cspell-trie-lib/src/lib/walker/index.ts
packages/cspell-trie-lib/src/lib/walker/walker.test.ts
packages/cspell-trie-lib/src/lib/walker/walker.ts
packages/cspell-trie-lib/src/lib/walker/walkerTypes.ts

When making suggestions, sort the ones where the first letter changes further down the list.

fix: Fix first letter insert costs on suggestions.

---

packages/cspell-lib/src/LanguageIds.test.ts
packages/cspell-lib/src/LanguageIds.ts

fix: Make sure ext `.R` is detected as an R file.

---

packages/cspell-eslint-plugin/fixtures/with-errors/sampleESM.mjs
packages/cspell-eslint-plugin/fixtures/with-errors/strings.ts
packages/cspell-eslint-plugin/src/_auto_generated_/options.schema.json
packages/cspell-eslint-plugin/src/cspell-eslint-plugin.ts
packages/cspell-eslint-plugin/src/index.test.ts
packages/cspell-eslint-plugin/src/index.ts
packages/cspell-eslint-plugin/src/options.ts
packages/cspell-lib/src/textValidation/docValidator.ts
test-packages/test-cspell-eslint-plugin/cspell.json
test-packages/test-cspell-eslint-plugin/src/file.js
test-packages/test-cspell-eslint-plugin/src/index.ts
test-packages/test-cspell-eslint-plugin/src/myReader.ts
test-packages/test-cspell-eslint-plugin/src/reader.ts

Options:
- ignoreImports
- checkIdentifiers
- checkStrings
- checkStringTemplates
- checkComments

dev: Support eslint-plugin options

---

.github/workflows/codeql-analysis.yml
.github/workflows/coverage.yml
.github/workflows/cspell-action.yml
.github/workflows/cspell-cli.yml
.github/workflows/cspell4-integration-update.yml
.github/workflows/integration-test.yml
.github/workflows/issues-lock.yml
.github/workflows/lint-docs.yml
.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/release-drafter.yml
.github/workflows/test-build-docs.yml
.github/workflows/test.yml
.github/workflows/update-dependencies-cspell4.yml
.github/workflows/update-dependencies.yml
.github/workflows/update-docs.yml
.github/workflows/update-integration-snapshots.yml
.github/workflows/version.yml

ci: Set permissions for GitHub actions

---

packages/cspell-tools/package-lock.json
packages/cspell-tools/package.json
packages/cspell-tools/src/app.ts
packages/cspell/package-lock.json
packages/cspell/package.json

This reverts commit b42bbdd28cbd8aefa28ce363b335fad781c37acf.

fix: Update to glob 8

---

.github/workflows/cspell4-integration-update.yml
.github/workflows/update-integration-snapshots.yml
integration-tests/package.json
integration-tests/src/run.ts
package.json

Try to reduce confusion when updating Integration test snapshots and repositories.

ci: refactor integration tests

---

rfc/rfc-0004 known issues/README.md
rfc/rfc-0004 known issues/types.ts

doc: RFC Known Issues

---

packages/cspell-grammar/fixtures/TypeScript/sample1.ts
packages/cspell-grammar/package.json
packages/cspell-grammar/src/__snapshots__/app.test.ts.snap
packages/cspell-grammar/src/app.test.ts
packages/cspell-grammar/src/app.ts
packages/cspell-grammar/src/grammars/typescript.ts
packages/cspell-grammar/src/parser/processors/procMatchingRule.ts
packages/cspell-grammar/src/parsers/typescript/TypeScriptParser.ts
packages/cspell-grammar/src/parsers/typescript/__snapshots__/index.test.ts.snap
packages/cspell-grammar/src/parsers/typescript/index.test.ts

fix: Update grammar app

---

cspell.code-workspace
packages/cspell-service-bus/src/SystemServiceBus.test.ts
packages/cspell-service-bus/src/SystemServiceBus.ts
packages/cspell-service-bus/src/__snapshots__/SystemServiceBus.test.ts.snap
packages/cspell-service-bus/src/__snapshots__/index.test.ts.snap
packages/cspell-service-bus/src/assert.test.ts
packages/cspell-service-bus/src/assert.ts
packages/cspell-service-bus/src/bus.test.ts
packages/cspell-service-bus/src/bus.ts
packages/cspell-service-bus/src/index.ts
packages/cspell-service-bus/src/request.test.ts
packages/cspell-service-bus/src/request.ts

- Add a concept of a SystemServiceBus
- Be able to register Subsystems
- Be able to register subsystem handlers

fix: Add SystemServiceBus

---

packages/cspell/src/application.ts
packages/cspell/src/commandLint.ts
packages/cspell/src/index.ts
packages/cspell/src/lint/LintRequest.ts
packages/cspell/src/options.ts

- Make the reporter optional for linting.
- Use the cli-reporter as default.

feat: Support a default reporter when linting.

---

packages/cspell-eslint-plugin/README.md
packages/cspell-eslint-plugin/cspell.json
packages/cspell-eslint-plugin/fixtures/samples/react/sample.jsx
packages/cspell-eslint-plugin/fixtures/samples/react/sample.tsx
packages/cspell-eslint-plugin/fixtures/with-errors/react/sample.jsx
packages/cspell-eslint-plugin/fixtures/with-errors/react/sample.tsx
packages/cspell-eslint-plugin/package-lock.json
packages/cspell-eslint-plugin/package.json
packages/cspell-eslint-plugin/src/_auto_generated_/options.schema.json
packages/cspell-eslint-plugin/src/cspell-eslint-plugin.ts
packages/cspell-eslint-plugin/src/index.test.ts
packages/cspell-eslint-plugin/src/options.ts
packages/cspell-eslint-plugin/tsconfig.json

- New Option: `checkJSXText` defaults to `true`.
fixes: #3342

feat: Support spell checking of JSX/TSX Text

---

package.json
packages/cspell-lib/src/Settings/InDocSettings.test.ts
packages/cspell-lib/src/Settings/InDocSettings.ts

Restore old behavior until the best approach is clear.

fix: directive words

---

doc-generator/package.json
pnpm-lock.yaml

Related to issues:
- https://github.com/tgreyuk/typedoc-plugin-markdown/issues/344
- https://github.com/TypeStrong/typedoc/issues/2051

chore: fix doc build by locking typedoc version

---

packages/cspell-lib/src/LanguageIds.ts

It seems the language definition of CMake is missing.
https://cmake.org/

feat: add awareness of CMake

---

doc-generator/package.json
pnpm-lock.yaml

chore: Unlock typedoc version

---

packages/cspell-tools/src/FeatureFlags/FeatureFlags.ts
packages/cspell-tools/src/FeatureFlags/__snapshots__/parseFlags.test.ts.snap
packages/cspell-tools/src/FeatureFlags/parseFlags.test.ts
packages/cspell-tools/src/FeatureFlags/parseFlags.ts
packages/cspell-tools/src/app.test.ts
packages/cspell-tools/src/compiler/__snapshots__/compile.test.ts.snap
packages/cspell-tools/src/compiler/__snapshots__/createCompileRequest.test.ts.snap
packages/cspell-tools/src/compiler/compile.test.ts
packages/cspell-tools/src/compiler/compile.ts
packages/cspell-tools/src/compiler/config.test.ts
packages/cspell-tools/src/compiler/config.ts
packages/cspell-tools/src/compiler/createCompileRequest.test.ts
packages/cspell-tools/src/compiler/createCompileRequest.ts
packages/cspell-tools/src/compiler/processCompileAction.ts
packages/cspell-tools/src/compiler/wordListCompiler.test.ts
packages/cspell-tools/src/test/TestHelper.ts

Improve code coverage and testing.

refactor: clean up cspell-tools

---

packages/cspell-trie-lib/src/lib/SimpleDictionaryParser.test.ts
packages/cspell-trie-lib/src/lib/SimpleDictionaryParser.ts
packages/cspell-trie-lib/src/lib/io/importExportV3.ts
packages/cspell-trie-lib/src/lib/io/importExportV4.ts

fix: remove look-behind from trie library.

---

packages/cspell/src/lint/lint.ts
packages/cspell/src/util/constants.ts
packages/cspell/src/util/fileHelper.test.ts
packages/cspell/src/util/fileHelper.ts
packages/cspell/src/util/glob.ts

Support using `stdin://filename` and `file://./filename` on the command line.
fixes: #4084

feat: support `stdin://` and `file://`  protocols

---

packages/cspell-eslint-plugin/README.md

docs: Improve ESLint Plugin README.me

---

packages/cspell-lib/fixtures/dictionaries/inline/cspell.config.yaml
packages/cspell/README.md

docs: Minor doc fixes

---

packages/cspell-lib/src/LanguageIds.test.ts
packages/cspell-lib/src/LanguageIds.ts

fix: Add `.webm` to know file types

---

cspell.code-workspace
packages/dynamic-import/lib/dynamicImport.js

fix: Do not use `node:`

---

packages/cspell-lib/package.json
packages/cspell-tools/package.json
pnpm-lock.yaml

See: https://github.com/cosmiconfig/cosmiconfig/issues/291

chore: Lock cosmic config

---

package.json
packages/cspell-lib/package.json
packages/cspell-tools/package.json
pnpm-lock.yaml
test-packages/cspell-lib/test-cspell-lib-rollup/lib/chalk.js
test-packages/cspell-lib/test-cspell-lib-rollup/package.json
test-packages/cspell-lib/test-cspell-lib-rollup/rollup.config.mjs

fix: Update cosmic config

---

integration-tests/snapshots/Azure/azure-rest-api-specs/snapshot.txt
integration-tests/snapshots/MartinThoma/LaTeX-examples/report.yaml
integration-tests/snapshots/MartinThoma/LaTeX-examples/snapshot.txt
packages/cspell-dictionary/src/SpellingDictionary/CachingDictionary.test.ts
packages/cspell-dictionary/src/SpellingDictionary/CachingDictionary.ts
packages/cspell-lib/api/api.d.ts
packages/cspell-lib/fixtures/docValidator/sample-with-common-errors.md
packages/cspell-lib/src/lib/Models/ValidationIssue.ts
packages/cspell-lib/src/lib/__snapshots__/index.test.ts.snap
packages/cspell-lib/src/lib/spellCheckFile.test.ts
packages/cspell-lib/src/lib/textValidation/ValidationTypes.ts
packages/cspell-lib/src/lib/textValidation/docValidator.test.ts
packages/cspell-lib/src/lib/textValidation/docValidator.ts
packages/cspell-lib/src/lib/textValidation/lineValidatorFactory.test.ts
packages/cspell-lib/src/lib/textValidation/lineValidatorFactory.ts
packages/cspell-lib/src/lib/textValidation/textValidator.test.ts
packages/cspell-lib/src/lib/textValidation/textValidator.ts
packages/cspell-lib/src/lib/util/textRegex.ts

feat: return preferred suggestions when validating text

---

packages/cspell-lib/package.json
packages/cspell-tools/package.json
pnpm-lock.yaml

fixes https://github.com/streetsidesoftware/vscode-spell-checker/issues/2583

fix: Update cosmiconfig to fix config loading issue.

---

packages/cspell-lib/package.json
packages/cspell-tools/package.json
pnpm-lock.yaml

Workaround for:
- https://github.com/cosmiconfig/cosmiconfig/issues/296
- https://github.com/cosmiconfig/cosmiconfig/issues/297
- https://github.com/cosmiconfig/cosmiconfig/issues/299

fix: lock cosmiconfig to 8.0.0

---

integration-tests/package.json
package.json
pnpm-lock.yaml

chore: Update Dependencies

---

packages/cspell/fixtures/features/reporter/README.md
packages/cspell/fixtures/features/reporter/cspell.config.yaml
packages/cspell/package.json
packages/cspell/src/app/__snapshots__/app.test.ts.snap
packages/cspell/src/app/app.test.ts
packages/dynamic-import/src/esm/dynamicImport.mts
pnpm-lock.yaml

fix: Fix dynamic loader on Windows

---

README.md

Video: https://www.youtube.com/watch?v=w8gGi3aeVpc

Added link for video presentation on Youtube

---

packages/cspell-lib/src/lib/LanguageIds.ts

fix: Do not spell check `.heic` files.

---

packages/cspell-tools/src/app.test.ts
packages/cspell-tools/src/compiler/readers/readTextFile.ts
packages/cspell-tools/src/compiler/writeTextToFile.ts
packages/cspell-tools/src/gzip/compressFiles.test.ts
packages/cspell-tools/src/gzip/compressFiles.ts
packages/cspell-tools/src/gzip/index.ts

fix (cspell-tools): normalize .gz output

---

package.json
pnpm-lock.yaml
test-packages/cspell-eslint-plugin/test-cspell-eslint-plugin/fixtures/file.js

The project seem dead: https://github.com/smonn/globcat/issues/144

chore: remove dependency upon globcat

---

packages/cspell-eslint-plugin/src/plugin/cspell-eslint-plugin.cts

fix: Protect against missing sourceCode

---

packages/cspell-lib/api/api.d.ts
packages/cspell-lib/src/lib/textValidation/docValidator.test.ts
packages/cspell-lib/src/lib/textValidation/docValidator.ts
packages/cspell-lib/src/lib/trace.ts
packages/cspell-lib/src/lib/util/TextRange.ts

Add/expose:
- trace - to trace a word to a dictionary
- getCheckedTextRanges

fix: API: Update DocValidator

---

packages/cspell-io/samples/link.txt
packages/cspell-io/src/VirtualFS.ts
packages/cspell-io/src/VirtualFs.test.ts
packages/cspell-io/src/handlers/node/file.ts
packages/cspell-io/src/models/Stats.ts
packages/cspell-lib/src/lib/Settings/Controller/configLoader/configSearch.test.ts
packages/cspell-lib/src/lib/Settings/Controller/configLoader/configSearch.ts
test-fixtures/issues/issue-5120/.config
test-fixtures/issues/issue-5120/.config-actual/cspell.config.yaml
test-fixtures/issues/issue-5120/README.md
test-fixtures/issues/issue-5120/docs/README.md
test-fixtures/issues/issue-5120/docs/cspell.actual.yaml
test-fixtures/issues/issue-5120/docs/cspell.config.yaml

fix: handle symbolic links to config files

---

packages/cspell-trie-lib/src/lib/distance/__snapshots__/weightedMaps.test.ts.snap
packages/cspell-trie-lib/src/lib/io/__snapshots__/importExportV3.test.ts.snap
packages/cspell-trie-lib/src/lib/io/__snapshots__/importExportV4.test.ts.snap
packages/cspell/src/app/__snapshots__/app.test.ts.snap
packages/cspell/src/app/emitters/__snapshots__/suggestionsEmitter.test.ts.snap
vitest.config.mts

Related to https://github.com/vitest-dev/vitest/issues/3955

test: improve snapshots

---

packages/Samples/package.json
packages/cspell-bundled-dicts/package.json
packages/cspell-code-snippets/package.json
packages/cspell-config-lib/package.json
packages/cspell-dictionary/package.json
packages/cspell-eslint-plugin/package.json
packages/cspell-gitignore/package.json
packages/cspell-glob/package.json
packages/cspell-grammar/package.json
packages/cspell-io/package.json
packages/cspell-json-reporter/package.json
packages/cspell-lib/package.json
packages/cspell-pipe/package.json
packages/cspell-resolver/package.json
packages/cspell-service-bus/package.json
packages/cspell-strong-weak-map/package.json
packages/cspell-tools/package.json
packages/cspell-trie-lib/package.json
packages/cspell-trie/package.json
packages/cspell-types/package.json
packages/cspell/package.json
packages/dynamic-import/package.json
packages/hunspell-reader/package.json
scripts/update-package-json.mjs

see: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository

chore: Remove extraneous `git+` form url

---

cspell.schema.json
packages/cspell-lib/src/lib/Settings/CSpellSettingsServer.ts
packages/cspell-lib/src/lib/__snapshots__/index.test.ts.snap
packages/cspell-types/cspell.schema.json
packages/cspell-types/src/CSpellSettingsDef.ts
packages/cspell-types/src/configFields.ts

Add config field `enabledFileTypes ` to replace `enableFiletypes ` and `enabledLanguageIds `.

fix: Add config field `enabledFileTypes `

---

website/_scripts/extract-properties.mjs
website/_scripts/jsconfig.json

Extract Markdown from Schema file

docs: Extract Markdown from cspell.schema.json

---

.github/workflows/smoke-test.yml
.github/workflows/test.yml
cspell.code-workspace
packages/cspell-io/package.json
packages/cspell-io/src/node/file/url.test.ts
packages/cspell-io/src/node/file/url.ts
packages/cspell-lib/package.json
packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLoader.test.ts
packages/cspell-lib/src/lib/util/url.test.ts
packages/cspell-lib/src/lib/util/url.ts
packages/cspell-url/.gitignore
packages/cspell-url/CHANGELOG.md
packages/cspell-url/LICENSE
packages/cspell-url/README.md
packages/cspell-url/package.json
packages/cspell-url/src/dataUrl.mts
packages/cspell-url/src/fileUrl.mts
packages/cspell-url/src/fileUrl.test.mts
packages/cspell-url/src/index.mts
packages/cspell-url/src/index.test.mts
packages/cspell-url/src/url.mts
packages/cspell-url/src/url.test.mts
packages/cspell-url/tsconfig.json
pnpm-lock.yaml

Move URL methods into a common library.

feat: Add library `@cspell/url`

---

.prettierignore

Change the top level `.prettierignore` to ignore auto generated content.

chore: Update .prettierignore

---

website/_scripts/extract-properties.mjs

Create an `inject` template function to help with keeping indention consistant.
Co-authored-by: Felix Moeser <amanoji@users.noreply.github.com>

docs: Use `inject` template function

---

.gitattributes
packages/cspell-lib/api/api.d.ts
packages/cspell-lib/src/lib/textValidation/traceWord.ts
packages/cspell-lib/src/lib/trace.test.ts
packages/cspell-lib/src/lib/trace.ts
packages/cspell/src/app/__snapshots__/app.test.ts.snap
packages/cspell/src/app/commandTrace.ts
packages/cspell/src/app/emitters/suggestionsEmitter.ts
packages/cspell/src/app/emitters/traceEmitter.test.ts
packages/cspell/src/app/emitters/traceEmitter.ts
packages/cspell/src/app/util/pad.test.ts
packages/cspell/src/app/util/pad.ts
packages/cspell/src/app/util/table.ts
packages/cspell/src/app/util/util.test.ts
packages/cspell/src/app/util/util.ts

- Fix case sensitive tracing.
- Display preferred corrections when they are available.

fix: Make sure case sensitive trace works as expected.

---

README.md
docs/_includes/generated-docs/README.md

See: https://www.linkedin.com/posts/liorgrossman_today-i-am-writing-to-share-that-weve-made-activity-7051208392559771648-etA3/

docs: Remove references to OpenBase

---

packages/cspell/src/app/cli-reporter.ts

fix: Always set the color to white

---

packages/cspell-io/src/index.ts
packages/cspell-lib/src/lib/util/findUpFromUrl.ts

chore: Remove duplicate findUp

---

packages/cspell-glob/src/GlobMatcher.test.ts
packages/cspell-glob/src/globHelper.test.ts
packages/cspell-glob/src/globHelper.ts
packages/cspell/src/app/util/glob.test.ts

fix: Correctly handle relative globs

---

docs/docs/installation.md
website/docs/installation.md

docs: fix grammar issue.

---

packages/cspell-eslint-plugin/src/plugin/cspell-eslint-plugin.cts

fix: Remove timeout in ESLint plugin

---

integration-tests/snapshots/eslint/eslint/report.yaml
integration-tests/snapshots/eslint/eslint/snapshot.txt
packages/cspell-lib/src/lib/textValidation/lineValidatorFactory.test.ts
packages/cspell-lib/src/lib/textValidation/lineValidatorFactory.ts

fix: some letters have multiple char codes.

---

packages/cspell-eslint-plugin/package.json
packages/cspell-gitignore/src/GitIgnore.ts
packages/cspell-gitignore/src/GitIgnoreFile.test.ts
packages/cspell-gitignore/src/GitIgnoreFile.ts
packages/cspell-gitignore/src/findRepoRoot.test.ts
packages/cspell-url/src/url.mts
packages/cspell-url/src/url.test.mts
packages/cspell/src/app/cli-reporter.ts
pnpm-lock.yaml
test-packages/cspell/test-cspell-stdin/cspell.config.yaml
test-packages/cspell/test-cspell-stdin/package.json

fix: Issue with stdin and .gitignore

---

website/docs/Configuration/auto_properties.md

* Changes found when running `pnpm gen-docs` while working on #7094

docs: Update generated auto_properties.md

---

cspell.schema.json
packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionary.test.ts
packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionary.ts
packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryCollection.test.ts
packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryCollection.ts
packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryFromTrie.ts
packages/cspell-dictionary/src/SpellingDictionary/SuggestOptions.ts
packages/cspell-eslint-plugin/src/generated/schema.cts
packages/cspell-lib/samples/ignore-forbidden-dutch-words/README.md
packages/cspell-lib/samples/ignore-forbidden-dutch-words/cspell.config.mjs
packages/cspell-lib/src/lib/Settings/DictionarySettings.ts
packages/cspell-lib/src/lib/test/dutch.spec.ts
packages/cspell-lib/src/lib/test/dutch2.spec.ts
packages/cspell-trie-lib/api/api.d.ts
packages/cspell-trie-lib/src/lib/ITrie.ts
packages/cspell-trie-lib/src/lib/ITrieNode/find.test.ts
packages/cspell-trie-lib/src/lib/ITrieNode/find.ts
packages/cspell-trie-lib/src/lib/ITrieNode/index.ts
packages/cspell-trie-lib/src/lib/index.ts
packages/cspell-trie-lib/src/lib/suggestions/genSuggestionsOptions.ts
packages/cspell-trie-lib/src/lib/suggestions/suggest.ts
packages/cspell-trie-lib/src/lib/suggestions/suggestAStar.ts
packages/cspell-trie-lib/src/lib/suggestions/suggestCollector.ts
packages/cspell-trie-lib/src/lib/trie.ts
packages/cspell-types/cspell.schema.json
packages/cspell-types/src/DictionaryDefinition.ts

Related to: 
- https://github.com/streetsidesoftware/vscode-spell-checker/issues/3810
- https://github.com/streetsidesoftware/vscode-spell-checker/issues/1765
- #7181

feat: Be able to ignore forbidden words in a dictionary

---

packages/cspell-glob/package.json
packages/cspell-glob/src/GlobMatcher.test.ts
packages/cspell-glob/src/GlobMatcher.ts
packages/cspell-glob/src/__snapshots__/index.test.ts.snap
packages/cspell-glob/src/globHelper.ts
packages/cspell-glob/src/index.ts
packages/cspell/src/app/util/glob.test.ts
packages/cspell/src/app/util/glob.ts
pnpm-lock.yaml

fix: Workaround picomatch bug

---

package.json
packages/dynamic-import/src/esm/index.test.mts
packages/dynamic-import/src/test/index.test.ts
pnpm-lock.yaml

Vitest changed the Error code.

chore: Update vitest

---

packages/cspell/package.json
packages/cspell/src/app/application.test.ts
packages/cspell/src/app/util/fileHelper.test.ts
packages/cspell/src/app/util/fileHelper.ts
packages/cspell/src/app/util/glob.test.ts
pnpm-lock.yaml

https://github.com/sindresorhus/get-stdin
Can't test on local, hope it won't break tests.

fix: Replace `get-stdin` with native alternative

---

scripts/gen-release.mjs
scripts/package.json

Support replacing existing tags in a CHANGELOG

chore: support CHANGELOG update

---

packages/cspell/src/app/__snapshots__/app.test.ts.snap
packages/cspell/src/app/emitters/dictionaryListEmitter.ts
packages/cspell/src/app/util/pad.ts

It was incorrectly trimming ansi strings.

fix: cspell trace output

---

packages/cspell-lib/docs/configuration.md

docs: `cspell.config.mjs` is actually supported

---

website/docs/Configuration/patterns.md

Better support finding code blocks, fixes a bug where preceding whitespace on previous lines was taken into consideration incorrectly. Also supports nested code blocks

Update example patterns.md - improved fence support
