src/exclusionHelper.ts
This PR adds support for [Visual Studio Live Share](http://aka.ms/vsls), by allowing spell checking to work against `vsls:` files, which is the scheme for documents on the "guest side" of a Live Share collaboration session. This ensures that developers who rely on the Code Spell Checker extension, to continue benefiting from it when pairing with another developer.
An equivalent change will need to be made in the [VS Code extension](https://github.com/Jason-Rev/vscode-spell-checker), which I will send out separately.
// CC @Jason3S
=> Adding support for Visual Studio Live Share

src/exclusionHelper.ts
Since making PR #28, we've added support to Visual Studio Live Share which allows language services to be remoted from the host (i.e. the developer that shared) to all of their guests. In order to optimize for the scenario where the host and guest both have the Code Spell Checker extension installed, we only want the host's to be generating diagnostics, since it would have full access to the project. Therefore, this PR undoes #28, in order to provide a better Live Share experience. Apologies for the churn!
=> [Live Share] Remove VSLS from supported scheme list

dictionaries/softwareTerms.txt
Add software terms "composable", "rebasing", and "changeset" 💯.
resolves [#222 from vscode-spell-checker](https://github.com/Jason-Rev/vscode-spell-checker/issues/222)
=> Add software terms "composable", "rebasing", and "changeset"

src/Settings/DictionarySettings.ts
Import settings and others are using `path.resolve()`.
I am pleased that you will also allow dictionary paths.
=> using path.resolve() for dictionary paths

bin.js, package.json
Fixes a problem with non-existent `bin` file when the project is cloned and installed. See https://github.com/Jason3S/cspell/issues/53#issuecomment-404451827
=> Fix bin problem on npm install

.pre-commit-hooks.yaml, .travis.yml
- Allows use of cspell as a pre-commit hook.
- Tests that hook works by running it on current repo
Fixes: #56
=> Added pre-commit hook definition

src/app.ts
Added ability to hide summary information in console application. For my project I just wanted to remove CSpell summary information in that case, hope this might be useful for other people too.
=> Add '--no-summary' option to command line application

dictionaries/powershell.txt
They are built-in enum words. For more information, see the following links:
* [About Execution Policies](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6)
* [ExecutionPolicy Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.executionpolicy?view=powershellsdk-1.1.0)
* [ExecutionPolicyScope Enum](https://docs.microsoft.com/en-us/dotnet/api/microsoft.powershell.executionpolicyscope?view=powershellsdk-1.1.0)
=> Add PowerShell ExecutionPolicy words

packages/cspell/src/Settings/DictionarySettings.test.ts, packages/cspell/src/Settings/DictionarySettings.ts
This allows configuration files to be used across multiple machines where absolute paths may differ.
Please let me know if you have any objections to the test. It feels a bit weird to re-use the default settings that way, but it is less verbose than creating a new settings object just for this test.
=> Resolve paths beginning with tilde as $HOME

packages/cspell-lib/dictionaries/softwareTerms.txt
"Snackbar" has become a common term used to refer to UI elements showing notifications and such. 
[Snackbars on Google's Material Design Website](https://material.io/design/components/snackbars.html#)
I've added snackbar to the software terms dictionary, hopefully this is the appropriate dictionary to include the term 🙂 
Thanks!
=> Add snackbar to softwareTerms dictionary

packages/cspell-lib/dictionaries/softwareTerms.txt
I've added "repo" (the short form of repository) to the software terms dictionary, hopefully this is the appropriate dictionary to include the term 🙂
Thanks!
=> Add repo to software terms dictionary

packages/cspell-lib/dictionaries/filetypes.txt, packages/cspell-lib/src/LanguageIds.ts
Adds `apiblueprint` language ID as specified in [vscode-apielements](https://github.com/XVincentX/vscode-apielements).
=> Adds apiblueprint to languageIds

packages/cspell-trie-lib/src/lib/walker.ts
:wave: love the vscode extension. Just started moving it to my CI for the TypeScript website in https://github.com/orta/danger-plugin-spellcheck/pull/20  
This PR makes this library usable in a project using TypeScript 3.6. ( Because the d.ts files are shipped with types which don't pass ) very likely these changes to tighten the inference on iterators are what broke it - https://github.com/Microsoft/TypeScript/issues/11375
=> Adds a ? to the HintedWalkerIterator interface for TS 3.6

cspell.schema.json, packages/cspell-lib/src/Settings/CSpellSettingsDef.ts, packages/cspell-lib/src/Settings/DictionarySettings.ts
A dictionary definition only needs a path. The `file` property is no longer needed.
=> fix: Correct the DictionaryDefinition to how it is actually used.

packages/cspell/.vscode/launch.json, packages/cspell/src/application.ts, packages/cspell/test/mocha.opts
=> fix(cspell): Fixes files getting skipped if there are multiple files listed in the command line.

packages/cspell-lib/dictionaries/miscTerms.txt
I frequently use this term for tests ([e.g.](https://github.com/typescript-eslint/typescript-eslint/pull/2099/files#diff-609e45e04d808afd08830c4ae5224b31R112)), and I humbly request that it be added to `miscTerms`.  I cannot find any mispellings of other words that are proximate.  [context](https://en.wikipedia.org/wiki/Ziltoid_the_Omniscient)
Thank you for your consideration :)
=> adds Ziltoid to miscTerms list

packages/cspell-lib/config/cspell-default.json, packages/cspell-lib/dictionaries/filetypes.txt, packages/cspell-lib/dictionaries/miscTerms.txt, packages/cspell-lib/src/LanguageIds.ts, packages/cspell-lib/src/Settings/DefaultSettings.ts, packages/cspell-trie/samples/softwareTerms.txt
[MDX][mdx] is a pretty useful extension of markdown that allows using JSX and imports directly within markdown files. It's been around for a few years now, but gaining more momentum from being used in projects such as Gatsby and Docz.
[mdx]: https://github.com/mdx-js/mdx
=> feat: add mdx support

.vscode/launch.json, cspell.schema.json, packages/cspell-glob/tsconfig.json, packages/cspell-io/tsconfig.json, packages/cspell-lib/src/Settings/CSpellSettingsDef.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts, packages/cspell-lib/src/Settings/DefaultSettings.ts, packages/cspell-lib/src/Settings/RegExpPatterns.test.ts, packages/cspell-lib/src/Settings/RegExpPatterns.ts, packages/cspell-lib/tsconfig.json, packages/cspell-tools/tsconfig.json, packages/cspell-trie-lib/tsconfig.json, packages/cspell-trie/tsconfig.json, packages/cspell-trie2-lib/tsconfig.json, packages/cspell-util-bundle/tsconfig.json, packages/cspell/tsconfig.json
- feat: Add ability to have multiple expressions in a pattern
- fix: Improve the speed of the cspell disable tests
It is now possible to use an array of regexp when defining a pattern:
```json
"patterns": [
{ "name": "strings", "pattern": ["'.*?'", "\".*\""] }
]
```
=> feat: Improved Spelling guards

packages/cspell-lib/src/Settings/InDocSettings.ts
Without the whitespace added to the regex it was allowing things like `cspell:languagetoset fr` to be valid and take effect.
=> Enforce whitespace after language in-doc setting

packages/cspell-lib/package-lock.json, packages/cspell-lib/package.json, packages/cspell-lib/samples/linked/cspell-import-missing.json, packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
This change to the config import resolution is backwards compatible with the current resolution, so there are no breaking changes.
When using npm 7 workspaces (or any monorepo structure that does not explicitly symlink every dependency) cspell fails to resolve shared configs that are installed at the workspace root.
cspell now uses a relative require which makes use of the Node.js resolution algorithm. This means that a sharable config may now also specify a "main" field in `package.json` instead of requiring users to explicitly use a complete filename.
So now instead of this with the explicit filename:
```json
{
"import": ["node_modules/my-cspell-config-package/cspell.json"]
}
```
A user can do this, as long as `cspell.json` (or any other filename) is defined as the value for `main` or …
=> fix: import resolution adjustment to support npm v7 workspaces

packages/cspell-glob/package-lock.json, packages/cspell-glob/package.json, packages/cspell-io/package-lock.json, packages/cspell-io/package.json, packages/cspell-lib/package-lock.json, packages/cspell-lib/package.json, packages/cspell-tools/package-lock.json, packages/cspell-tools/package.json, packages/cspell-trie-lib/package-lock.json, packages/cspell-trie-lib/package.json, packages/cspell-trie/package-lock.json, packages/cspell-trie/package.json, packages/cspell-trie2-lib/package-lock.json, packages/cspell-trie2-lib/package.json, packages/cspell-util-bundle/package-lock.json, packages/cspell-util-bundle/package.json, packages/cspell/package-lock.json, packages/cspell/package.json
Also update the on explict older version in util-bundle
=> chore: Explicit rimraf devDependency

.github/workflows/lint.yml
Other jobs use explicit branch filters alread, but Lint job is running
twice for dependabot branch/prs
=> chore: Skip linting on Dependabot pushes

cspell-dict.txt, package-lock.json, package.json, packages/cspell-lib/package-lock.json, packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryCollection.test.ts, packages/cspell-lib/src/util/util.test.ts, packages/cspell-util-bundle/package.json, packages/cspell-util-bundle/src/xregexp.ts
cspell-util-bundle forced consumers to have a copy for XRegExp to get the types.
=> ci: remove unnecessary dependency upon xregexp types

.github/workflows/coverage.yml
Trying to see if it will get rid of the "overall coveralls/coveralls" job that usually marked as failed with a reduction of coverage
=> chore: Remove parallel coveralls since not in matrix

.github/workflows/lint.yml
GitHub actions path globs are more basic in their regexs https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-file-paths
=> chore: Fix Lint CI globs

package.json
Depenedncy of jest-runner, but not by any package directly
=> chore: Remove hard reference to source-map-support

package-lock.json, package.json
Only used by cspell-lib, so reduces the bump in both places
=> chore: Remove ts-json-schema-generator at root

.github/workflows/coverage.yml
This reverts commit 76c80f0762e0542fe33e9d458dd3826b9281bf67.
Uploading to Coverall one module at a time screws coveralls.
By using parallel, it considers all the packages part of the same build.
Otherwise they are considered separate builds, see image:
=> Revert "chore: Remove parallel coveralls since not in matrix (#561)"

package.json, packages/cspell-util-bundle/package-lock.json
There was a small change in cspell-util-bundle that was included
=> chore: use rimraf instead of rm -rf in update-packages

.github/workflows/lint.yml
Noticed in #593 that it's still building those branches. Looked at another repo with the setup and it used the double asterisks instead so trying that here
=> fix: globbing for dependabot PR filtering

integration-tests/package-lock.json, integration-tests/package.json, package.json
When updating packages, use `lerna bootstrap --no-ci` so that the package-lock files get updated.
Note: `--no-ci` used to be the default.
=> ci: use bootstrap --no-ci

.prettierignore, package-lock.json, package.json, packages/cspell-lib/package-lock.json, packages/cspell-lib/package.json
Left all the general dev packages used in the root and supporting tools, but removed the ones already installed in the child packages explicitly now
=> chore: Shake out root packages included in sub-packages

packages/cspell/src/app.test.ts, packages/cspell/src/app.ts
The error code should be set if:
`check` fails to find files or has errors
`trace` fails to find a word in any dictionary
=> fix: make sure the error code is correctly set

.prettierignore, packages/cspell-lib/package-lock.json, packages/cspell-lib/package.json, packages/cspell-lib/src/Settings/CSpellSettingsDef.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts, packages/cspell-lib/src/Settings/GlobalSettings.test.ts, packages/cspell-lib/src/Settings/GlobalSettings.ts, packages/cspell-lib/src/Settings/link.test.ts, packages/cspell-lib/src/Settings/link.ts, packages/cspell-lib/src/__mocks__/configstore.ts, packages/cspell-lib/src/index.ts, packages/cspell-lib/src/util/resolveFile.ts, packages/cspell/.vscode/launch.json, packages/cspell/package-lock.json, packages/cspell/package.json, packages/cspell/src/app.test.ts, packages/cspell/src/app.ts, packages/cspell/src/application.test.ts, packages/cspell/src/application.ts, packages/cspell/src/link.test.ts, packages/cspell/src/link.ts, packages/cspell/src/util/table.test.ts, packages/cspell/src/util/table.ts, packages/cspell/tsconfig.json
Add `link` command to the cli:
The `link` command will:
- `list` - will list any globally linked configuration files
- `add` - will add a configuration file to the global configuration.
- `remove` - will remove a configuration file from the global configuration.
Example to add `cspell.json` form the home directory to the global configuration. 
```sh
cspell link add ~/cspell.json
```
Sample output:
```
Adding:
filename                 | errors
/Users/jason/cspell.json |   
```
Example List
```sh
cspell link
```
Sample output:
```
id    | package           | name              | filename                                                | dictionaries | errors
|                   |                   | /Users/jason/cspell.json                                |              |       
de-de | …
```
=> feat: Add link command

.github/workflows/update-dependencies.yml
Just scratching my own itch, since Actions don't run on forks by default, but this means this job will only run on your repo even when the fork has Actions turned on
=> chore: Don't run dependency updates on forks

.github/dependabot.yml, .github/workflows/update-dependencies.yml
The Dependabot security updates should still come in more frequently if required, but this pushes it so the other updates only come once a week instead of daily
=> chore: Make NPM updates weekly

packages/cspell-glob/package.json
Change from lib to dist in a previous PR, but I missed this ref
=> fix: cleanup folder for cspell-glob

packages/cspell/README.md
cspell doc page in Mega-Linter is there -> https://nvuillam.github.io/mega-linter/descriptors/spell_cspell/
Please tell me if you require any update :)
=> CI/CD README section: Add Mega-Linter

.github/workflows/codeql-analysis.yml, cspell-dict.txt, integration-tests/snapshots/django/django/snapshot.txt, integration-tests/snapshots/typescript-cheatsheets/react/snapshot.txt, packages/cspell-lib/package-lock.json, packages/cspell-lib/package.json, packages/cspell-lib/samples/linked/cspell.js, packages/cspell-lib/samples/linked/text.txt, packages/cspell-lib/samples/yaml-config/cspell.yaml, packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts, packages/cspell/src/application.ts
Related to #847
cspell will search for the following configuration files:
```
'package.json',
'cspell.json',
'cSpell.json',
'.cspell.json',
'.vscode/cspell.json',
'.vscode/cSpell.json',
'.vscode/.cspell.json',
'.cSpell.json',
'cspell.yaml',
'cspell.yml',
'cspell.js',
'cspell.cjs',
```
=> feat: support .yaml and .js configuration files

packages/cspell-glob/src/GlobMatcher.test.ts, packages/cspell-glob/src/GlobMatcher.ts
For historical reasons, cspell-glob assumed two roots:
1. the one passed in which defaulted to the current working directory
2. the FS root on any drive.
This happened because it was sometimes difficult to determine the root inside the VS Code extension.
In cspell 5, there is a shift with the `ignorePaths` meaning to be relative to the location of the file that defined them.
It will also be possible to define the root for the `ignorePaths` within the configuration file.
=> feat: cspell-glob matches only files under the root

cspell.schema.json, packages/cspell-lib/cspell.config.json, packages/cspell-lib/docs/configuration.md, packages/cspell-lib/samples/js-config/cspell.config.js, packages/cspell-lib/samples/js-config/custom-words.txt, packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts, packages/cspell-lib/src/Settings/ImportError.ts, packages/cspell-lib/src/index.ts, packages/cspell-lib/src/spellCheckFile.test.ts, packages/cspell-lib/src/spellCheckFile.ts, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/settings/CSpellSettingsDef.ts, packages/cspell/src/CSpellApplicationConfiguration.ts, packages/cspell/src/app.ts, packages/cspell/src/application.test.ts, packages/cspell/src/application.ts, packages/cspell/src/options.ts
The spell checker will look for the following configuration files.
- `.cspell.json`
- `cspell.json`
- `.cSpell.json`
- `cSpell.json`
- `.vscode/cspell.json`
- `.vscode/cSpell.json`
- `.vscode/.cspell.json`
- `cspell.config.js`
- `cspell.config.cjs`
- `cspell.config.json`
- `cspell.config.yaml`
- `cspell.config.yml`
- `cspell.yaml`
- `cspell.yml`
While spell checking files, the spell checker will look for the nearest configuration file in the directory hierarchy.
This allows for folder level configurations to be honored.
It is possible to stop this behavior by adding adding `"noConfigSearch": true` to the top level configuration.
A Monorepo Example:
```
repo-root
├── cspell.config.json
├─┬ packages
│ ├─┬ package-A
│ │ ├── cspell.json
│ │ ├── README.md
│ │ └── CHANGELOG.md
│ ├─┬ package-B
│ …
```
=> feat: Support local configuration files

packages/cspell-lib/src/Settings/LanguageSettings.test.ts, packages/cspell-lib/src/Settings/LanguageSettings.ts
Support the the following:
```json
"languageSettings": [
{
"languageId": "!markdown",
"flagWords": ["colour"]
}
]
```
We means, forbid "colour" in all file types except `markdown`.
=> feat: Support negation matches in languageSettings for languageIds

package-lock.json, package.json, packages/cspell-glob/src/GlobMatcher.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
Glob patterns in `ignorePaths` use the same logic as `.gitignore` files.
1. Glob patterns shall be considered relative to the file they are defined in.
1. It is possible to define a `globRoot` to override the default behavior.
If `globRoot` is `undefined` it will default to the location of the configuration file. `globRoot` can be relative to the file location.
If a `project/.settings/cspell.json` file has a `globRoot` of `..`, then the `globRoot` will become `project`. To have the root be the current working directory, use `${cwd}`.
1. It is also possible to define a root for each glob pattern.
The spell checker will look for the following configuration files.
```javascript
/*
* Logic of the locations:
* - Support backward compatibility with the VS Code Spell Checker
*   the spell …
```
=> fix: adjust order in which files are loaded.

packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
See [fix: Adjust the way glob roots are calculated](https://github.com/streetsidesoftware/cspell/commit/d1a7fa78759257d692598bf712254201ed0dd126#commitcomment-47719278)
@timwsuqld I'm rolling back those changes from that commit.
It will not impact your "new" setup, but it will do a better job of preserving the old behavior.
=> fix: issue cause by commit d1a7fa7

.github/workflows/integration-test.yml, .github/workflows/test.yml, integration-tests/config/config.json, integration-tests/snapshots/googleapis/google-cloud-cpp/snapshot.txt, packages/cspell/src/__snapshots__/app.test.ts.snap, packages/cspell/src/app.test.ts, packages/cspell/src/app.ts, packages/cspell/src/emitters.ts, packages/cspell/src/lint.ts
Command line exclusions were broken.
=> fix: Fix command line exclusions

.github/workflows/lint.yml
The build was broken because a dependabot pull_request changed the eslint rules.
=> ci: run lint on every pull_request

packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
This PR adds support for the [`packageProp`](https://github.com/davidtheclark/cosmiconfig#packageprop) in [`cosmiconfig`](https://github.com/davidtheclark/cosmiconfig).
This feature enables developers to remove yet another boilerplate file from their apps.
=> feat: Support `packageProp` in `cosmiconfig`

packages/cspell/CHANGELOG.md
Make sure the `CHANGELOG.md` has the notes from changes to `cspell-lib`.
=> fix: Update CHANGELOG.md

.github/workflows/coverage.yml
Revert "build(deps): bump codecov/codecov-action from 1.5.2 to 2.0.1(#1438)"
This reverts commit 2f911009406dfc0f6689c03dbf08d7dfdce9841a.
=> ci: Fix coverage upload breakage

packages/cspell-lib/package-lock.json, packages/cspell-lib/package.json, packages/cspell-lib/src/Settings/GlobalSettings.test.ts, packages/cspell-lib/src/Settings/GlobalSettings.ts, packages/cspell-lib/src/types.d.ts
=> fix: error output when configstore dir not accessible.

packages/cspell-lib/src/SpellingDictionary/SpellingDictionary.ts, packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryCollection.ts, packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryFromTrie.ts, packages/cspell-lib/src/SpellingDictionary/createSpellingDictionary.ts, packages/cspell-lib/src/textValidator.test.ts, packages/cspell-lib/src/textValidator.ts, packages/cspell-lib/src/trace.ts, packages/cspell-lib/src/util/Memorizer.test.ts, packages/cspell-lib/src/util/Memorizer.ts, packages/cspell-lib/src/validator.test.ts, packages/cspell-lib/src/validator.ts, packages/cspell/cSpell.json, packages/cspell/samples/.cspell.json, packages/cspell/samples/forbidden-words.txt, packages/cspell/samples/src/sample-with-forbidden-words.md, packages/cspell/src/__snapshots__/app.test.ts.snap, packages/cspell/src/app.test.ts, packages/cspell/src/app.ts, packages/cspell/src/emitters.ts, packages/cspell/src/lint.ts
There are several ways to mark a word as forbidden:
1. In a custom word list with words beginning with `!`.
```
!forbiddenWord
```
2. In `words` section of `cspell` configuration:
```
"words": [
"!forbiddenWord",
"configstore"
],
```
3. In `flagWords` section of `cspell` configuration:
```
"flagWords": ["forbiddenWord"]
```
Sometimes it is necessary to allow a word even if it is forbidden.
```js
/**
* Do not mark `forbiddenWord` as incorrect.
* cspell:ignore forbiddenWord
*/
```
```jsonc
{
"ignoreWords": ["forbiddenWord"]
}
```
=> feat: Support forbidden words in dictionaries

cspell.schema.json, integration-tests/cspell.json, packages/Samples/tests/exclude_dictionary/cspell.json, packages/cspell-lib/docs/configuration.md, packages/cspell-lib/samples/.cspell.json, packages/cspell-lib/samples/comments_only/cpp_strings_and_comments.cspell.json, packages/cspell-lib/samples/linked/cspell-dutch.json, packages/cspell-lib/samples/linked/cspell-imports.json, packages/cspell-tools/cSpell.json, packages/cspell-types/ajv.config.js, packages/cspell-types/cspell.schema.json, packages/cspell-types/package.json, packages/cspell-types/src/settings/CSpellSettingsDef.ts, packages/cspell/README.md, packages/cspell/samples/comments_only/cpp_strings_and_comments.cspell.json, packages/cspell/samples/linked/cspell-dutch.json, packages/cspell/samples/linked/cspell-imports.json
* dev: make sure cspell config file version is "0.2"
* fix: Improve config docs
* Use `deprecationMessage` instead of `deprecatedMessage`
See: [deprecatedMessage renamed to deprecationMessage · Issue #16409 · microsoft/vscode](https://github.com/microsoft/vscode/issues/16409)
=> dev: make sure cspell config files use version "0.2"

packages/cspell-trie-lib/src/lib/find.dutch.test.ts, packages/cspell-trie-lib/src/lib/find.test.ts, packages/cspell-trie-lib/src/lib/find.ts
have `forbidden` be undefined if it was not calculated.
=> fix: clean up find results

packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts, packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryCollection.test.ts, packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryFromTrie.ts
fix issue where some dictionaries (nl-nl) could cause slow suggestions
Using compound words can be very very slow to generate suggestions.
The current Dutch dictionary has compounds turned on. This caused very very slow suggestions to be generated.
=> fix: fix slow suggestions with some dictionaries

.github/workflows/test.yml
Related to:
* [`Check failed: !holder_map.has_named_interceptor().` when running `jest` · Issue #40030 · nodejs/node](https://github.com/nodejs/node/issues/40030)
=> test: fix github-actions

.gitignore, packages/cspell-bundled-dicts/tsconfig.json, packages/cspell-dynamic-loader/tsconfig.json, packages/cspell-glob/.npmignore, packages/cspell-glob/tsconfig.json, packages/cspell-io/.npmignore, packages/cspell-io/tsconfig.json, packages/cspell-lib/.npmignore, packages/cspell-lib/tsconfig.json, packages/cspell-tools/.npmignore, packages/cspell-tools/tsconfig.json, packages/cspell-trie-lib/.npmignore, packages/cspell-trie-lib/tsconfig.json, packages/cspell-trie/.npmignore, packages/cspell-trie/tsconfig.json, packages/cspell-trie2-lib/.npmignore, packages/cspell-trie2-lib/tsconfig.json, packages/cspell-types/tsconfig.json, packages/cspell/.npmignore, packages/cspell/tsconfig.json, packages/hunspell-reader/.npmignore, packages/hunspell-reader/tsconfig.json, test-packages/test-cspell-glob/tsconfig.json, test-packages/test-cspell-io/tsconfig.json, test-packages/test-cspell-lib-webpack/tsconfig.json, test-packages/test-cspell-lib/tsconfig.json, test-packages/test-cspell-tools/tsconfig.json, test-packages/test-cspell/tsconfig.json
TypeScript support incremental build mode which caches build results in filesystem (see [here)](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html)
Enabling this speeds up `npm run build` more than 2x on my machine.
=> enable incremental typescript builds

packages/cspell-trie-lib/src/lib/timer.ts
to allow Browserify/Webpack to work.
Related to #1704
=> Explicitly import `hrtime` from `process`

integration-tests/package-lock.json, packages/cspell-bundled-dicts/package-lock.json, packages/cspell-bundled-dicts/package.json, packages/cspell-dynamic-loader/package-lock.json, packages/cspell-glob/package-lock.json, packages/cspell-io/package-lock.json, packages/cspell-json-reporter/package-lock.json, packages/cspell-lib/package-lock.json, packages/cspell-tools/package-lock.json, packages/cspell-trie-lib/package-lock.json, packages/cspell-trie/package-lock.json, packages/cspell-trie2-lib/package-lock.json, packages/cspell-types/package-lock.json, packages/cspell/package-lock.json, packages/hunspell-reader/package-lock.json, test-packages/test-cspell-lib-webpack/package-lock.json
=> fix: Make dict-en-gb version 2 optional because of license.

packages/cspell-bundled-dicts/package-lock.json, packages/cspell-bundled-dicts/package.json
=> fix: Roll back update to `@cspell/dict-en-gb@2`

packages/cspell-lib/src/Settings/InDocSettings.test.ts, packages/cspell-lib/src/util/text.test.ts, packages/cspell-lib/src/util/text.ts
`u` is over 100x slower to run. So, only add it if no flags are given.
Logic: If they know enough to add flags, then they can add `u` if needed.
Related to: #1699
=> fix: Patterns - only add `u` if no flags are given

integration-tests/snapshots/php/php-src/snapshot.txt, integration-tests/src/check.ts, packages/cspell/src/cli-reporter.ts
When issues are displayed, show the filename, not the URI.
=> fix: Display filenames instead of URI's

packages/cspell-trie-lib/src/lib/suggest-en.test.ts
Make the timeout a bit longer because this test is flaky on Mac / Windows runners.
=> test: Update suggest-en.test.ts

.github/dependabot.yml
I didn't add it to the 4 branch, because the site can only run off one branch
=> chore: Add Dependabot for Gemfile

docs/configuration/index.md
I think it will be nice if there is an example to setup `patterns` setting is the docs.
It may help us understand the structure of the `patterns` from a quick glance.
PS. The patterns used in the example is from the test file of this feature (https://github.com/streetsidesoftware/cspell/blob/5375c73e47/packages/cspell-lib/src/Settings/patterns.test.ts#L7-L18)
=> docs: Add example of patterns configuration

packages/cspell-gitignore/README.md, packages/cspell-gitignore/src/GitIgnore.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts
* fix: Update `cspell-gitignore` README
* fix: normalize `gitignoreRoot`s
=> fix: Update gitignore README and normalize roots

cspell.schema.json, packages/cspell-lib/samples/words.txt, packages/cspell-lib/src/SpellingDictionary/DictionaryLoader.test.ts, packages/cspell-lib/src/SpellingDictionary/DictionaryLoader.ts, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/CSpellSettingsDef.ts
Each line in the file will be split based upon simple code splitting rules.
=> dev: Support Legacy dictionary type

packages/cspell/src/__snapshots__/app.test.ts.snap, packages/cspell/src/commandLint.ts
- replace `--wordsOnly` option with `--words-only`
- hide `--wordsOnly` option but keep it working.
=> fix: Change `--wordsOnly` option to `--words-only`

packages/cspell/src/application.ts, packages/cspell/src/lint/LintRequest.ts, packages/cspell/src/lint/index.ts, packages/cspell/src/lint/lint.test.ts, packages/cspell/src/lint/lint.ts, packages/cspell/src/options.ts, packages/cspell/src/util/cache/CSpellLintResultCache.ts, packages/cspell/src/util/cache/CacheOptions.ts, packages/cspell/src/util/cache/DiskCache.ts, packages/cspell/src/util/cache/DummyCache.ts, packages/cspell/src/util/cache/createCache.ts, packages/cspell/src/util/cache/index.ts
- Remove any circular import references.
- Move interfaces next to the supporting code.
=> dev: Refactor cache files

cspell-dict.txt, packages/cspell-trie-lib/cspell.json, packages/cspell-trie-lib/src/lib/TrieBuilder.test.ts, packages/cspell-trie-lib/src/lib/TrieBuilder.ts, packages/cspell-trie-lib/src/lib/index.ts
When compiling Estonian, it would cause node to run out of keys due to caching highly repetitive suffixes.
=> fix: cspell-tools - limit memory usage when build dictionaries

packages/cspell/package.json, packages/cspell/src/app.ts
Change addressing #1984.
@Jason3S, is this how you'd like it handled?
=> feat: report error and fail for unsupported NodeJS versions (#1984)

cspell.schema.json, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/CSpellSettingsDef.ts
While setting up `cspell` for one project, I noticed few typos in JSON schema.
Fixed those quickly, but then I saw that some descriptions end with a full stop and some do not. Just couldn’t leave it.
At first this minor inconsistency did not look important, but the result makes the schema look somewhat nicer.
=> style(schema, types): fix few typos and add full stops at the end of all descriptions

packages/cspell/src/fileHelper.test.ts, packages/cspell/src/fileHelper.ts, packages/cspell/src/lint/lint.test.ts, packages/cspell/src/lint/lint.ts, packages/cspell/src/options.ts, packages/cspell/src/util/errors.test.ts, packages/cspell/src/util/errors.ts
fix: #2285 
- Continue processing the list of files even if some are missing.
- Report on any missing files.
- error code is based upon `--no-must-file-files` option.
=> fix: Handle missing files when spell checking from a file list.

rfc/rfc-0002 improve dictionary suggestions/README.md
I think this maybe a typo and should be therefore.
REF: https://www.thefreedictionary.com/therefore-vs-therefor.htm
Also:
- https://github.com/streetsidesoftware/cspell/blob/b76fd122825f7ea1ef48dcf1d8da72a21ec0b17b/packages/cspell-lib/samples/forbid-words/README.md
- https://github.com/streetsidesoftware/cspell/blob/b76fd122825f7ea1ef48dcf1d8da72a21ec0b17b/packages/cspell-lib/samples/forbid-words/cspell.json
=> fix therefore typo

packages/cspell-gitignore/src/GitIgnore.ts, packages/cspell/src/app.test.ts, packages/cspell/src/application.test.ts, packages/cspell/src/application.ts, packages/cspell/src/lint/lint.ts, packages/cspell/src/util/async.test.ts, packages/cspell/src/util/async.ts, packages/cspell/src/util/cache/CSpellLintResultCache.ts, packages/cspell/src/util/cache/DiskCache.test.ts, packages/cspell/src/util/cache/DiskCache.ts, packages/cspell/src/util/cache/getConfigHash.ts, packages/cspell/src/util/fileHelper.test.ts, packages/cspell/src/util/fileHelper.ts, packages/cspell/src/util/stdin.test.ts, packages/cspell/src/util/util.test.ts, packages/cspell/src/util/util.ts
=> feat: Support REPL style reading from stdin 

packages/cspell/src/lint/lint.test.ts, packages/cspell/src/lint/lint.ts
=> fix: Show an error if a glob starts/ends with a single quote

packages/cspell-tools/src/compiler/wordListCompiler.test.ts, packages/cspell-tools/src/compiler/wordListCompiler.ts
In `--split` mode, the compiler would loose free floating accents.
=> fix: Make sure cspell-tool-cli keeps accents

cspell.json, packages/cspell-types/src/CSpellReporter.ts, packages/cspell/src/__snapshots__/app.test.ts.snap, packages/cspell/src/app.test.ts, packages/cspell/src/cli-reporter.ts, packages/cspell/src/lint/lint.ts, packages/cspell/src/util/InMemoryReporter.ts, test-packages/test-cspell/src/index.ts
- If caching is on, report number of cached files.
- if progress in on, signal the start of processing a file. This helps with finding very slow files.
=> fix: Improve cli summary and progress

.eslintrc.test.plugin.js, package-lock.json, package.json, packages/cspell-lib/api/api.d.ts, packages/cspell-lib/fixtures/docValidator/sample-with-cspell-directives.ts, packages/cspell-lib/src/Models/CSpellSettingsInternalDef.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts, packages/cspell-lib/src/Settings/InDocSettings.test.ts, packages/cspell-lib/src/Settings/RegExpPatterns.test.ts, packages/cspell-lib/src/Settings/patterns.test.ts, packages/cspell-lib/src/Settings/patterns.ts, packages/cspell-lib/src/textValidation/docValidator.test.ts, packages/cspell-lib/src/textValidation/docValidator.ts, packages/cspell-lib/src/textValidation/textValidator.test.ts, packages/cspell-lib/src/textValidation/textValidator.ts, packages/cspell-lib/src/textValidation/validator.ts, packages/cspell-lib/src/util/TextRange.regexp.test.ts, packages/cspell-lib/src/util/TextRange.ts, packages/cspell-lib/src/util/timer.test.ts, packages/cspell-lib/src/util/timer.ts
Ignore Regexp were not being honored.
=> fix: eslint-plugin - fix issue with document directives

.github/workflows/coverage.yml, .github/workflows/cspell-action.yml, .github/workflows/cspell4-integration-update.yml, .github/workflows/issues-lock.yml, .github/workflows/release-drafter.yml, .github/workflows/update-dependencies-cspell4.yml, .github/workflows/update-dependencies.yml, .github/workflows/update-docs.yml, .github/workflows/update-integration-snapshots.yml
- Pinned actions by SHA https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
>Pin actions to a full length commit SHA
>Pinning an action to a full length commit SHA is currently the only way to use an action as an immutable release. Pinning to a particular SHA helps mitigate the risk of a bad actor adding a backdoor to the action's repository, as they would need to generate a SHA-1 collision for a valid Git object payload.
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
[How do I validate these pinned actions?](https://gist.github.com/naveensrinivasan/ca008c07279176acce28969fb77d056f)
Also, dependabot supports upgrading based on SHA. https://github.com/ossf/scorecard/pull/1700
GitHub's own …
=> Pin actions to a full length commit SHA

packages/cspell/src/util/async.ts, packages/cspell/src/util/fileHelper.ts
Fix relative path names when reading the file list from `stdin`.
=> fix: relative path name

packages/cspell-pipe/src/operators/filter.test.ts, packages/cspell-pipe/src/operators/filter.ts, packages/cspell/src/lint/lint.ts, packages/cspell/src/util/async.ts, packages/cspell/src/util/fileHelper.test.ts, packages/cspell/src/util/fileHelper.ts
The following would cause an error when there was a subdirectory.
```sh
ls -1 | cspell "**" --cache
```
=> fix: Ignore directories when checking files

.github/workflows/deploy-website.yml
Break up the workflow into two parts:
1. Build with read permissions
2. Deploy with write permissions
=> ci: improve deploy website workflow permissions

packages/cspell-lib/src/spellCheckFile.ts, packages/cspell/fixtures/issue-2998/cspell.json, packages/cspell/fixtures/issue-2998/fix-words.txt, packages/cspell/fixtures/issue-2998/run.sh, packages/cspell/src/__snapshots__/app.test.ts.snap, packages/cspell/src/app.test.ts
=> fix: missing language-id

cspell.code-workspace, cspell.schema.json, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/CSpellSettingsDef.ts
Related to: [Support dictionary files without a `.txt` ending. · Issue #2001 · streetsidesoftware/vscode-spell-checker](https://github.com/streetsidesoftware/vscode-spell-checker/issues/2001)
=> fix: Remove `.txt` restriction from dictionary files.

.github/workflows/coverage.yml, .github/workflows/cspell-action.yml, .github/workflows/cspell-cli.yml, .github/workflows/cspell5-update-dependencies.yml, .github/workflows/cspell5-update-dictionaries.yml, .github/workflows/cspell5-update-integration-repositories.yml, .github/workflows/deploy-website.yml, .github/workflows/integration-test.yml, .github/workflows/lint-docs.yml, .github/workflows/lint.yml, .github/workflows/reuseable-build-dist-cache.yml, .github/workflows/reuseable-load-integrations-repo-list.yml, .github/workflows/test-build-docs.yml, .github/workflows/test.yml, .github/workflows/update-dependencies.yml, .github/workflows/update-dictionaries.yml, .github/workflows/update-docs.yml, .github/workflows/update-integration-repositories.yml, .github/workflows/website-lint.yml, .github/workflows/website-test.yml
Unpin to match the other core actions and noticed a few old checkout ones
=> chore: unpin setup-node and bump leftover actions/checkout

packages/cspell-lib/src/suggestions.test.ts
This is to address failures due to test timeouts on MacOS runners.
=> test: Increase the timeout for suggestions test.

packages/cspell-json-reporter/README.md
Related to [#3111](https://github.com/streetsidesoftware/cspell/discussions/3111#discussioncomment-3011536)
=> fix: Update reporter README

packages/cspell-lib/api/api.d.ts, packages/cspell-lib/src/Models/CSpellSettingsInternalDef.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts, packages/cspell-lib/src/textValidation/docValidator.ts, packages/cspell-types/src/CSpellSettingsDef.ts
Parser references must be strings.
=> fix: Do not allow nested Parser functions.

integration-tests/src/repositoryHelper.ts, packages/cspell-glob/src/GlobMatcher.test.ts, packages/cspell-glob/src/GlobMatcher.ts, packages/cspell-glob/src/GlobMatcherTypes.ts, packages/cspell-glob/src/globHelper.test.ts, packages/cspell-glob/src/globHelper.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts, packages/cspell-lib/src/exclusionHelper.test.ts, packages/cspell/src/util/glob.test.ts
**Minor Breakage**
Globs starting with `**` are considered global and will not be evaluated relative to the containing configuration file's path.
To make a relative glob, start it with `/`, like `/**`.
=> feat: Support global globs

cspell.schema.json, packages/cspell-bundled-dicts/cspell-default.config.ts, packages/cspell-lib/api/api.d.ts, packages/cspell-lib/src/Models/CSpellSettingsInternalDef.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts, packages/cspell-lib/src/__snapshots__/index.test.ts.snap, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/CSpellSettingsDef.ts, packages/cspell-types/src/configFields.ts, packages/cspell-types/src/types.ts
Plugin type is not compatible with serialization. The solution was to pull it out into `AdvancedCSpellSettings`
=> fix: Pull out `plugins` to avoid conflict

packages/cspell-bundled-dicts/cspell-default.config.js, packages/cspell-bundled-dicts/cspell-default.config.ts, packages/cspell-bundled-dicts/package-lock.json, packages/cspell-bundled-dicts/package.json, packages/cspell-grammar/src/index.ts, packages/cspell-grammar/src/parsers/index.ts, packages/cspell-lib/package-lock.json, packages/cspell-lib/package.json, packages/cspell-lib/src/Settings/DefaultSettings.ts
Late binding of parsers is creating an issue with the config loader.
This will be fixed later, since late binding is the desired behavior.
=> fix: Do not late bind parsers

packages/cspell-eslint-plugin/fixtures/with-errors/creepyData.dict.txt, packages/cspell-eslint-plugin/src/_auto_generated_/options.schema.json, packages/cspell-eslint-plugin/src/cspell-eslint-plugin.ts, packages/cspell-eslint-plugin/src/customWordList.ts, packages/cspell-eslint-plugin/src/index.test.ts, packages/cspell-eslint-plugin/src/options.ts, test-packages/test-cspell-eslint-plugin/.eslintrc.js
Add the ability to add words to a custom dictionary.
Mostly fixes: #3233, but is flaky because it is using an unsupported technique to detect when a fix has been applied.
-  Option: `customWordListFile`
**Experimental**: Specify a path to a custom word list file (A utf-8 text file with one word per line). This file is used to present the option to add words.
=> feat(cspell-eslint-plugin): Experimental Add word to dictionary

packages/cspell-eslint-plugin/src/_auto_generated_/options.schema.json, packages/cspell-eslint-plugin/src/cspell-eslint-plugin.ts, packages/cspell-eslint-plugin/src/options.ts
=> fix: Mark adding words to custom dictionary experimental

packages/cspell-eslint-plugin/package.json, packages/cspell-eslint-plugin/src/_auto_generated_/options.schema.json
Remove references from schema because ESLint does not support them.
fixes: #3269
=> fix: Fix ESLint schema

cspell-dict.txt, cspell.schema.json, packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryCollection.test.ts, packages/cspell-lib/src/SpellingDictionary/SpellingDictionaryFromTrie.ts, packages/cspell-lib/src/SpellingDictionary/charset.ts, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/DictionaryInformation.ts
Added the ability to specify characters to be ignored (removed) from a word before checking the word in the dictionary.
Related to Aribic Harakat vowel accents.
https://github.com/streetsidesoftware/cspell-dicts/issues/1314
=> feat: Support Ignoring characters before checking

packages/cspell-pipe/src/__snapshots__/index.test.ts.snap, packages/cspell-pipe/src/helpers/__snapshots__/index.test.ts.snap, packages/cspell-pipe/src/helpers/distribute.test.ts, packages/cspell-pipe/src/helpers/distribute.ts, packages/cspell-pipe/src/helpers/index.ts, packages/cspell-pipe/src/helpers/interleave.test.ts, packages/cspell-pipe/src/helpers/interleave.ts, packages/cspell-pipe/src/index.ts, packages/cspell-pipe/src/operators/__snapshots__/index.test.ts.snap, packages/cspell-pipe/src/operators/append.test.ts, packages/cspell-pipe/src/operators/append.ts, packages/cspell-pipe/src/operators/index.test.ts, packages/cspell-pipe/src/operators/index.ts, packages/cspell-pipe/src/operators/joinStrings.ts, packages/cspell-pipe/src/operators/take.test.ts, packages/cspell-pipe/src/operators/take.ts
Operators / methods:
- append: be able to append values to the end of an iterator
- interleave: be able to interleave values.
- toDistributableIterable
Improve coverage.
=> fix(cspell-pipe): Add operators

packages/cspell-trie-lib/package.json, pnpm-lock.yaml
It was a devDependency, but parts of `cspell-trie-lib` import from it.  This brings it in line with how other packages in the repo (e.g. `@cspell/cspell-json-reporter`, `cspell-grammar`) depend on `@cspell/cspell-types`.
=> fix(cspell-trie-lib): move `@cspell/cspell-types`

packages/cspell-lib/src/Settings/InDocSettings.test.ts, packages/cspell-lib/src/Settings/InDocSettings.ts, packages/cspell-lib/src/textValidation/docValidator.test.ts
fix: #3080
- Support `dictionary` as alias of `dictionaries`.
- Improve Directive Validation support.
=> fix: Add directive `flag-word`

packages/cspell-bundled-dicts/cspell-default.config.js, packages/cspell-bundled-dicts/cspell-default.config.ts, packages/cspell-bundled-dicts/package.json, packages/cspell-bundled-dicts/test-samples/markdown.md
fix: #3588
Note:
This change will ignore anything in the `()` of a markdown link.
=> feat: Ignore markdown links

packages/cspell-lib/api/api.d.ts, packages/cspell-lib/src/Settings/patterns.test.ts, packages/cspell-lib/src/Settings/patterns.ts, packages/cspell-lib/src/util/text.ts, packages/cspell-lib/src/util/textRegex.test.ts, packages/cspell-lib/src/util/textRegex.ts, packages/cspell/samples/config/yaml-regexp/README.md, packages/cspell/samples/config/yaml-regexp/cspell.config.yaml, packages/cspell/src/lint/lint.test.ts
This change might break some regexp patterns that have leading or trailing spaces and are NOT inside slashes, `/.../`.
```json
"ignoreRegExp": ["end of line\n"]
```
convert to:
```json
"ignoreRegExp": ["/end of line\n/g"]
```
Defining RegExp Patterns in `.json` or `.yaml` CSpell config files has been difficult.
This feature makes it easier to define patterns in a `.yaml` file.
CSpell now supports the `x` - verbose flag.
```regexp
/
^(\s*`{3,}).*     # match the ```
[\s\S]*?          # the block of code
^\1               # end of the block
/gmx
```
Example of Ignoring code block in `markdown`.
**`cspell.config.yaml`**
```yaml
patterns:
- name: markdown_code_block
pattern: |
/
^(\s*`{3,}).*     # match the ```
[\s\S]*?          # the block of code
^\1               # end of the block
/gmx …
```
=> feat: Support Verbose Regexp Patterns

packages/cspell-lib/src/LanguageIds.ts
Added capitalised version of image extensions werent ignored, this PR fixes that, see below.
```js
c:\Users\kiera\OneDrive\Projects\Discord Bots\hullcss-discord-bot\src\images\gorbcelebration.PNG:12335:65 - Unknown word (JRNB)
c:\Users\kiera\OneDrive\Projects\Discord Bots\hullcss-discord-bot\src\images\gorbcelebration.PNG:12341:537 - Unknown word (momh)
c:\Users\kiera\OneDrive\Projects\Discord Bots\hullcss-discord-bot\src\images\gorbcelebration.PNG:12341:570 - Unknown word (cۚwu)
c:\Users\kiera\OneDrive\Projects\Discord Bots\hullcss-discord-bot\src\images\gorbcelebration.PNG:12341:964 - Unknown word (ЍRWC)
c:\Users\kiera\OneDrive\Projects\Discord Bots\hullcss-discord-bot\src\images\gorbcelebration.PNG:12342:161 - Unknown word (BވKx)
c:\Users\kiera\OneDrive\Projects\Discord …
```
=> fix: Capitalised image extensions not being ignored

integration-tests/package.json, packages/cspell-config-lib/package.json, packages/cspell-lib/package.json, packages/cspell/package.json, pnpm-lock.yaml
=> chore: Lock `vscode-uri` to 3.0.4

.github/workflows/test.yml
Some tests have started to fail when too much load is put on the host. Setting concurrency to 1 should help prevent that.
=> ci: limit the test concurrency to fix test timeouts due to overloaded hosts.

packages/cspell-lib/api/api.d.ts, packages/cspell-lib/src/FeatureFlags/FeatureFalgs.test.ts, packages/cspell-lib/src/FeatureFlags/FeatureFlags.ts, packages/cspell-lib/src/FeatureFlags/index.ts, packages/cspell-lib/src/__snapshots__/index.test.ts.snap, packages/cspell-lib/src/index.ts, packages/cspell/src/__snapshots__/app.test.ts.snap, packages/cspell/src/app.ts, packages/cspell/src/commandCheck.ts, packages/cspell/src/commandLint.ts, packages/cspell/src/commandSuggestion.ts, packages/cspell/src/commandTrace.ts, packages/cspell/src/featureFlags/featureFlags.test.ts, packages/cspell/src/featureFlags/featureFlags.ts, packages/cspell/src/featureFlags/index.ts, packages/cspell/src/options.ts
Feature flags are used to hide new Features and Behaviors until they are ready for release.
=> fix: Add Development Feature Flags

README.md
It has become too hard to automatically update the tools used by CSpell 5.x to build and test.
Due to this, all support for CSpell 5 has moved to paid support only.
=> doc: Drop Active Support for CSpell 5

.github/workflows/dependabot-recreate.yml
Instead of having Dependabot recreate all the PRs at the same time, the idea is to:
1. tag all of them with `dependabot:recreate`
2. later slowly mark them to be recreated.
=> ci: Reduce the cost of Dependabot PRs

packages/cspell-tools/src/compiler/__snapshots__/compile.test.ts.snap, packages/cspell-tools/src/compiler/wordListCompiler.test.ts, packages/cspell-tools/src/compiler/wordListParser.test.ts, packages/cspell-trie-lib/src/lib/SimpleDictionaryParser.test.ts, packages/cspell-trie-lib/src/lib/SimpleDictionaryParser.ts, packages/cspell-trie-lib/src/lib/suggestions/walker/hintedWalker.test.ts, packages/cspell-trie-lib/src/lib/trie.test.ts
Default `stripCaseAndAccentsKeepDuplicate` to `false` because it uses too much memory.
=> fix: Do not generate duplicate entries by default

cspell-dict.txt, packages/cspell-lib/package.json, packages/cspell-lib/src/SpellingDictionary/DictionaryController/DictionaryLoader.ts, packages/cspell-lib/src/util/StrongWeakMap.test.ts, packages/cspell-lib/src/util/StrongWeakMap.ts, packages/cspell-lib/tsconfig.json
Use Weak References to dictionaries to allow them to be garbage collected.
Minor Breakage: Requires Node 14.6 or higher instead of Node 14.
=> feat: Improve Memory Usage

packages/cspell-trie-lib/src/lib/io/importExportV4.test.ts, packages/cspell-trie-lib/src/lib/io/importExportV4.ts
Fixes and issue with non-base 10 radixes.
The parser assumed that the reference index was in base 10.
=> fix: trie-lib - fix issue with reference radix.

packages/cspell-dictionary/src/SpellingDictionary/Terms/index.ts, packages/cspell-dictionary/src/SpellingDictionary/Terms/terms.ts, packages/cspell-dictionary/src/SpellingDictionary/Typos/typos.ts, packages/cspell-dictionary/src/SpellingDictionary/Typos/typosParser.test.ts, packages/cspell-dictionary/src/SpellingDictionary/Typos/typosParser.ts, packages/cspell-dictionary/src/SpellingDictionary/Typos/util.test.ts, packages/cspell-dictionary/src/SpellingDictionary/Typos/util.ts
In the proposed Terms definition, flagged words have a value of `false` instead of `null`. `null` is reserved to ignore words. `true` is reserved to mean the word is ok.
=> fix: Adjust the Typos definition to match Terms

packages/cspell-lib/api/api.d.ts, packages/cspell-lib/src/Models/Suggestion.ts, packages/cspell-lib/src/Models/ValidationIssue.ts, packages/cspell-lib/src/Models/ValidationResult.ts, packages/cspell-lib/src/Settings/InDocSettings.ts, packages/cspell-lib/src/textValidation/ValidationTypes.ts, packages/cspell-lib/src/textValidation/__snapshots__/validator.test.ts.snap, packages/cspell-lib/src/textValidation/checkText.ts, packages/cspell-lib/src/textValidation/docValidator.test.ts, packages/cspell-lib/src/textValidation/docValidator.ts, packages/cspell-lib/src/textValidation/index.ts, packages/cspell-lib/src/textValidation/lineValidatorFactory.ts, packages/cspell-lib/src/textValidation/parsedText.ts, packages/cspell-lib/src/textValidation/textValidator.ts, packages/cspell-lib/src/textValidation/validator.test.ts, packages/cspell-lib/src/textValidation/validator.ts
To support AutoFix, it is necessary to distinguish which suggestions are preferred. Preferred suggestions are AutoFix candidates.
=> feat: Support preferred suggestions

packages/cspell/src/lint/lint.ts, packages/cspell/src/util/glob.ts
fixes: #2739
This feature makes the following equivalent:
- `cspell .` - `cspell "**"`
- `cspell .github` - `cspell ".github/**"`
- `cspell projects` - `cspell "projects/**"`
- `cspell projects\client` (windows) - `cspell "projects/client/**"`
Mixing Globs and directories does not work:
- `cspell "projects/*/src"` is not changed.
=> feat: Support spell checking whole directories.

docs/docs/command-trace.md
This PR fixes a trivial mistake in `command-trace.md`.
=> fix: Fix a typing mistake in docs

docs/configuration/index.md
This PR adds a config example in the documentation which demonstrates how to use dictionaries defined in remote files.
Along the lines it also fixes an issue in the example: The "name" of the dictionary was inconsistent. The three variants `corp-term`, `corp-terms` and `company-terms` were used. This, in my understanding would not have worked either way.
See also #4035
=> Add example for remote dictionaries

packages/cspell-eslint-plugin/package.json, packages/cspell-eslint-plugin/src/cspell-eslint-plugin.ts, packages/cspell-eslint-plugin/src/options.ts, packages/cspell-eslint-plugin/src/worker.ts, pnpm-lock.yaml, test-packages/cspell-eslint-plugin/test-cspell-eslint-plugin/.eslintrc.js, test-packages/cspell-eslint-plugin/test-cspell-eslint-plugin/fixtures/component.tsx, test-packages/cspell-eslint-plugin/test-cspell-eslint-plugin/package.json
Move the logic out of `cspell-eslint-plugin.ts` and into its own file.
The plan is to make an async version, but it needs to be in its own file and cannot call into eslint context.
=> refactor: move spell checking into worker

cspell.schema.json, integration-tests/repositories/cspell-reporter.json, packages/cspell-json-reporter/src/index.test.ts, packages/cspell-json-reporter/src/index.ts, packages/cspell-lib/src/Settings/Controller/configLoader/normalizeRawSettings.ts, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/CSpellReporter.ts, packages/cspell-types/src/CSpellSettingsDef.ts, packages/cspell-types/src/index.ts, packages/cspell/src/application.ts, packages/cspell/src/cli-reporter.ts, packages/cspell/src/lint/LintRequest.ts, packages/cspell/src/lint/lint.ts, packages/cspell/src/util/reporters.test.ts, packages/cspell/src/util/reporters.ts
If a configuration contains a custom reporter, the default cli reporter will no longer be called. The fix is to add `"default"` to the list of `"reporters"`.
<details>
<summary>Fix to Breakage</summary>
Old `cspell.json`
```js
//...
"reporters": ["./my-custom-reporter.cjs"]
```
Becomes
```js
//...
"reporters": ["./my-custom-reporter.cjs", "default"]
```
</details>
It is was not possible to disable the default cli reporter when using a custom reporter. This made custom reporters less useful in a CI/CD environment with structured logging.
If a custom reporter is defined, disable the default reporter. Allow the `"default"` reporter to be re-enabled by explicitly including it in the `"reporters"` list.
=> feat: Disable default reporter if another reporter has been defined.

packages/cspell-json-reporter/README.md, packages/cspell-json-reporter/src/CSpellJSONReporterOutput.ts, packages/cspell-json-reporter/src/CSpellJSONReporterSettings.ts, packages/cspell-json-reporter/src/__snapshots__/index.test.ts.snap, packages/cspell-json-reporter/src/index.test.ts, packages/cspell-json-reporter/src/index.ts, packages/cspell-json-reporter/src/utils/__snapshots__/validateSettings.test.ts.snap, packages/cspell-json-reporter/src/utils/validateSettings.test.ts, packages/cspell-json-reporter/src/utils/validateSettings.ts, packages/cspell-types/src/CSpellReporter.ts, packages/cspell/src/util/reporters.test.ts
Enable `@cspell/cspell-json-reporter` so that it can output to `stdout` and `stderr` as well as a file.
=> feat: JSON Reporter, support output to `stdout`

packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionary.ts, packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryCollection.ts, packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryMethods.ts, packages/cspell-lib/api/api.d.ts, packages/cspell-lib/src/Models/Suggestion.ts, packages/cspell-lib/src/Settings/LanguageSettings.test.ts, packages/cspell-lib/src/Settings/LanguageSettings.ts, packages/cspell-lib/src/suggestions.ts, packages/cspell-lib/src/textValidation/ValidateTextOptions.ts, packages/cspell-lib/src/textValidation/docValidator.ts, packages/cspell-lib/src/textValidation/index.ts, packages/cspell-lib/src/textValidation/settingsToValidateOptions.ts, packages/cspell-lib/src/textValidation/textValidator.test.ts, packages/cspell-lib/src/textValidation/validator.ts, packages/cspell-trie-lib/src/lib/suggestions/suggestCollector.ts, packages/cspell-types/src/CSpellReporter.ts, packages/cspell/cspell.json, packages/cspell/fixtures/features/typos/code.ts, packages/cspell/fixtures/features/typos/cspell.config.yaml, packages/cspell/fixtures/features/typos/test.md, packages/cspell/src/__snapshots__/app.test.ts.snap, packages/cspell/src/cli-reporter.ts, packages/cspell/src/emitters/suggestionsEmitter.ts, packages/cspell/src/lint/lint.ts
In order to support auto fix in the eslint-cspell-plugin, suggestions need to match the case of the word being replaced.
fixes #4147
=> feat: Emit suggestions matching source case

packages/cspell-lib/src/Settings/CSpellSettingsServer.test.ts, packages/cspell-lib/src/Settings/CSpellSettingsServer.ts, packages/cspell-lib/src/Settings/InDocSettings.test.ts, packages/cspell-lib/src/Settings/InDocSettings.ts
Do not merge in-doc words with config words to avoid unnecessary large dictionary creation.
=> fix: Reduce in-doc dictionary creation

docs/configuration/document-settings.md, packages/cspell/README.md
This word is normally spelled with two `m`.
=> doc: fix typo in 'programming'

packages/cspell/src/util/cache/fileEntryCache.ts
=> fix: `node:worker_threads` breaks on node 14

packages/cspell/src/util/cache/createCache.ts
The `universal` format was not getting read from the config file.
=> fix: Be able to read cache format from config

integration-tests/snapshots/MartinThoma/LaTeX-examples/report.yaml, integration-tests/snapshots/MartinThoma/LaTeX-examples/snapshot.txt, packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionary.ts, packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryFromTrie.test.ts, packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryFromTrie.ts, packages/cspell-dictionary/src/util/repMap.test.ts, packages/cspell-dictionary/src/util/repMap.ts, packages/cspell-trie-lib/src/__snapshots__/index.test.ts.snap, packages/cspell-trie-lib/src/lib/index.ts
It is possible to define a `repMap` in the dictionary definition. This allows for sub-string substitutions. It use to be an ALL or nothing option.
Old behavior:
- `Goerresstraße` -> `Görreßtraße` which won't match the correct word of `Görresstraße`.
New behavior:
- `Goerresstraße` -> `Goerresstraße`, `Goerreßtraße`, `Görresstraße`, `Görreßtraße`
Note, this is only applied to words being checked, not words in the dictionary.
Dictionary contains:
- `Görresstraße`
This also addresses these issues: 
- https://github.com/streetsidesoftware/cspell-dicts/issues/1842
- https://github.com/streetsidesoftware/cspell-dicts/issues/1176
=> feat: Support multiple `repMap` combinations

packages/cspell/src/app/__snapshots__/app.test.ts.snap, packages/cspell/src/app/app.test.ts, packages/cspell/src/app/cli-reporter.test.ts, packages/cspell/src/app/cli-reporter.ts, packages/cspell/src/app/commandLint.ts
**Minor Breakage:** the default command line output now includes preferred fixes. This might break CI/CD processes that parse the output. It is better if these systems use a custom reporter.
Use `--no-show-suggestions` to turn of displaying the fixes.
=> feat: report preferred fixes by default

packages/cspell-lib/src/lib/__snapshots__/index.test.ts.snap, packages/cspell-lib/src/lib/trace.test.ts, packages/cspell-lib/src/lib/util/__snapshots__/wordSplitter.test.ts.snap, packages/cspell-lib/src/lib/util/text.test.ts, packages/cspell-lib/src/lib/util/textRegex.test.ts, packages/cspell-lib/src/lib/util/textRegex.ts, packages/cspell-lib/src/lib/util/wordSplitter.test.ts, packages/cspell-lib/src/lib/util/wordSplitter.ts
Support words starting with `.` or digits.
It is now possible to match against the following types of words
dictionary:
- `.descvec`
- `99.9krock`
=> feat: Support words containing `.`

packages/cspell-trie-lib/src/lib/TrieBlob/README.md, packages/cspell-trie-lib/src/lib/TrieBlob/TrieBlob.test.ts, packages/cspell-trie-lib/src/lib/TrieBlob/TrieBlob.ts, packages/cspell-trie-lib/src/lib/TrieBlob/index.test.ts, packages/cspell-trie-lib/src/lib/TrieBlob/index.ts, packages/cspell-trie-lib/src/lib/TrieBuilder.ts, packages/cspell-trie-lib/src/lib/TrieNode.ts, packages/cspell-trie-lib/src/lib/compoundWalker.ts, packages/cspell-trie-lib/src/lib/consolidate.test.ts, packages/cspell-trie-lib/src/lib/consolidate.ts, packages/cspell-trie-lib/src/lib/convertToTrieRefNodes.ts, packages/cspell-trie-lib/src/lib/find.ts, packages/cspell-trie-lib/src/lib/flatten.ts, packages/cspell-trie-lib/src/lib/io/importExportV1.ts, packages/cspell-trie-lib/src/lib/io/importExportV2.ts, packages/cspell-trie-lib/src/lib/io/importExportV3.test.ts, packages/cspell-trie-lib/src/lib/io/importExportV3.ts, packages/cspell-trie-lib/src/lib/io/importExportV4.test.ts, packages/cspell-trie-lib/src/lib/io/importExportV4.ts, packages/cspell-trie-lib/src/lib/suggestions/suggestAStar.ts, packages/cspell-trie-lib/src/lib/trie-util.test.ts, packages/cspell-trie-lib/src/lib/trie-util.ts, packages/cspell-trie-lib/src/lib/trie.en.test.ts, packages/cspell-trie-lib/src/lib/trie.ts, packages/cspell-trie-lib/src/lib/walker/hintedWalker.ts, packages/cspell-trie-lib/src/lib/walker/walker.ts, packages/cspell-trie-lib/src/test/util.test.helper.ts
The internal structure of TrieNode has been changed to a plain object instead of using a Map. This has greatly reduced memory consumption.
=> feat!: Change the internal structure of a Trie

packages/cspell-tools/src/build.ts
An empty build targets list means all build targets should be built.
=> fix: Fix empty build target

packages/cspell/package.json, pnpm-lock.yaml
Related to #4639
This bug creeped in because cspell-types used to be purely types and didn't need to be packaged with cspell.
=> fix: make sure cspell-types are true dependencies

packages/cspell-tools/src/compile.test.ts, packages/cspell-tools/src/compile.ts, packages/cspell-tools/src/compiler/__snapshots__/createCompileRequest.test.ts.snap, packages/cspell-tools/src/compiler/createCompileRequest.test.ts, packages/cspell-tools/src/compiler/createCompileRequest.ts
If the config file was generated on windows, it would not work on Linux.
=> fix: cspell-tools: fix init option output

packages/cspell-dictionary/src/util/simpleCache.test.ts, packages/cspell-lib/src/lib/wordListHelper.ts, packages/cspell-tools/src/compiler/compile.ts, packages/cspell-trie-lib/api/api.d.ts, packages/cspell-trie-lib/src/lib/TrieBuilder.ts, packages/cspell-trie-lib/src/lib/TrieNode/trie-util.test.ts, packages/cspell-trie-lib/src/lib/TrieNode/trie-util.ts, packages/cspell-trie-lib/src/lib/consolidate.ts, packages/cspell-trie-lib/src/lib/utils/secondChanceCache.test.ts, packages/cspell-trie-lib/src/lib/utils/secondChanceCache.ts, packages/cspell/src/app/application.test.ts, packages/hunspell-reader/src/aff.ts
On large dictionaries it was possible for the Trie builder to create circular tries.
=> fix: Fix and issue with `.trie` builder

cspell.json, packages/cspell-eslint-plugin/README.md, packages/cspell-eslint-plugin/assets/options.schema.json, packages/cspell-eslint-plugin/cspell.config.yaml, packages/cspell-eslint-plugin/package.json, packages/cspell-eslint-plugin/src/common/options.ts, packages/cspell-eslint-plugin/src/plugin/defaultCheckOptions.ts, packages/cspell-eslint-plugin/src/plugin/index.test.ts, packages/cspell-eslint-plugin/src/worker/spellCheck.mts, pnpm-lock.yaml
hello. In addition to the file path option, an option has been added to make the eslint spell checker work normally even when word lists are entered.
If this option is added, it seems that the spell checker option can be applied immediately without having to create and read the file.
=> feat: Add customWords options

packages/cspell-grammar/package.json
Previously the 'homepage' in `package.json` for cspell-grammar erroneously pointed to the README for cspell-gitignore
=> update homepage for cspell-grammar

packages/cspell/src/app/__snapshots__/app.test.ts.snap, packages/cspell/src/app/commandLint.ts
Closes #4742 
Tests needs to be added, I'm not that familar with the repo, could you just pick up the rest? Thx! ❤️
=> feat: add quiet flag

packages/cspell-tools/src/app.test.ts, packages/cspell-tools/src/app.ts, packages/cspell-tools/src/gzip/compressFiles.test.ts, packages/cspell-tools/src/gzip/compressFiles.ts, packages/cspell-tools/src/gzip/gzip.ts, packages/cspell-tools/src/gzip/index.ts
Issues: .gz files were different based upon which OS they were build on. This creates problems with conditional builds.
Fix: Always set the OSFlag in the .gz file to Unix.
=> fix (cspell-tools): Set the OS flag to Unix in .gz files

.eslintrc.js, .prettierignore, cspell.json, cspell.schema.json, packages/cspell-eslint-plugin/assets/options.schema.json, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/CSpellSettingsDef.ts, packages/cspell-types/src/DictionaryInformation.ts, packages/cspell-types/src/InlineDictionary.ts, pnpm-lock.yaml, scripts/build-cspell-schema.mjs, scripts/lib-bundled/ts-json-schema-generator.cjs, scripts/package.json
Using `@markdownDescription` was messing description inheritance need in the VS Code Spell Checker extension.
=> fix: Remove `@markdownDescription` from types

packages/cspell-eslint-plugin/README.md
The property must be named `cspell`. If I name it `cSpell` I'm getting following error:
```sh
Oops! Something went wrong! :(
ESLint: 8.46.0
Error: Key "rules": Key "@cspell/spellchecker": 	Value {"words":[],"ignoreWords":[],"flagWords":[],"ignoreRegExpList":[],"includeRegExpList":[],"allowCompoundWords":true,"import":[],"dictionaries":[],"dictionaryDefinitions":[],"enabled":true} should NOT have additional properties.
```
When I name it `cspell` everything is working as expected. Furthermore it it also called `cspell` in your JSON schema: https://github.com/streetsidesoftware/cspell/blob/0c115fedd1050aa67531bc31a9bf81ee0e0c26e0/packages/cspell-eslint-plugin/assets/options.schema.json#L36
=> docs: Change property name in readme

.gitignore, cspell.schema.json, packages/cspell-eslint-plugin/assets/options.schema.json, packages/cspell-eslint-plugin/fixtures/issue-4870/.eslintrc.js, packages/cspell-eslint-plugin/fixtures/issue-4870/cspell.config.yaml, packages/cspell-eslint-plugin/fixtures/issue-4870/dictionaries/business-terminology.txt, packages/cspell-eslint-plugin/fixtures/issue-4870/sample.js, packages/cspell-eslint-plugin/package.json, packages/cspell-eslint-plugin/src/common/logger.cts, packages/cspell-eslint-plugin/src/common/options.cts, packages/cspell-eslint-plugin/src/plugin/cspell-eslint-plugin.cts, packages/cspell-eslint-plugin/src/plugin/defaultCheckOptions.cts, packages/cspell-eslint-plugin/src/plugin/index.test.cts, packages/cspell-eslint-plugin/src/worker/spellCheck.mts, packages/cspell-eslint-plugin/src/worker/types.cts, packages/cspell-eslint-plugin/src/worker/worker.mjs, packages/cspell-gitignore/src/__snapshots__/app.test.ts.snap, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/DictionaryDefinition.ts, pnpm-lock.yaml
fixes: #4870
- resolve the dictionary path based upon the cwd given to eslint
- Add tests for cspell settings.
- support logging to a file.
=> fix: eslint-plugin, make sure dictionary settings make it to cspell-lib

cspell.schema.json, packages/cspell-types/cspell.schema.json, scripts/build-cspell-schema.mjs
jsonc files allow trailing commas, so the schema needs to be updated.
=> fix: cspell.schema.json incorrect schema

docs/configuration/language-settings.md
=> Fix several typos in docs/configuration/language-settings.md

packages/cspell-io/src/VirtualFS.ts, packages/cspell-io/src/VirtualFs.test.ts, packages/cspell-io/src/__snapshots__/index.test.ts.snap, packages/cspell-io/src/common/CFileResource.test.ts, packages/cspell-io/src/common/CFileResource.ts, packages/cspell-io/src/common/index.ts, packages/cspell-io/src/index.ts
Add:
- writeFile
- getCapabilities
=> fix: Add endpoints to VirtualFS

packages/cspell-io/src/VirtualFS.ts, packages/cspell-io/src/VirtualFS/redirectProvider.test.ts, packages/cspell-io/src/VirtualFS/redirectProvider.ts, packages/cspell-io/src/VirtualFs.test.ts, packages/cspell-io/src/index.ts, packages/cspell-io/src/node/file/url.ts, packages/cspell-lib/api/api.d.ts, packages/cspell-lib/samples/README.md, packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLoader.test.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLoader.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/configSearch.test.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/configSearch.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/defaultConfigLoader.test.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/defaultConfigLoader.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/normalizeRawSettings.ts, packages/cspell-lib/src/lib/Settings/DefaultSettings.ts, packages/cspell-lib/src/lib/Settings/DictionarySettings.ts, packages/cspell-lib/src/lib/fileSystem.ts, packages/cspell-lib/src/lib/index.ts, packages/cspell-lib/src/lib/util/findUpFromUrl.ts, packages/cspell-lib/src/lib/util/resolveFile.ts, packages/cspell-lib/src/lib/util/resolveFileLegacy.test.ts, packages/cspell-lib/src/lib/util/resolveFileLegacy.ts
This PR is to add support for reading cspell configuration over `https` or a virtual file system used by VSCode.
It is not possible to load JavaScript files remotely until it is supported by NodeJS.
=> feat: Support loading remote configuration.

.github/workflows/update-dictionaries.yml
Each integration repo needed a unique storage key.
=> chore: fix update dictionary workflow

packages/cspell-lib/src/lib/util/Uri.test.ts, packages/cspell-lib/src/lib/util/Uri.ts
The uri encoding was overly aggressive. 
This change only has an impact if there are special characters in the path.
Like: `@$&+,=`.
=> fix: correct the URI encoding

packages/cspell-io/src/VirtualFS.ts, packages/cspell-lib/src/lib/Settings/DictionarySettings.ts, packages/cspell-lib/src/lib/SpellingDictionary/DictionaryController/DictionaryLoader.ts, packages/cspell-lib/src/lib/util/AutoResolve.test.ts, packages/cspell-lib/src/lib/util/AutoResolve.ts, packages/cspell-lib/src/lib/util/simpleCache.test.ts, packages/cspell-lib/src/lib/util/simpleCache.ts, packages/cspell-strong-weak-map/src/StrongWeakMap.test.ts, packages/cspell-strong-weak-map/src/StrongWeakMap.ts
This change reduces dictionary reload for long running processes.
The dictionary loader uses a WeakMap to keep dictionaries. This is very effective for keeping the memory size down when using the command-line tool. But, it also throws out dictionaries too soon when the spell checker is used as part of a server. To address this, the dictionary loader keep the most recent 10-20 loaded dictionaries in memory.
=> fix: Improve caching of dictionaries

packages/cspell-config-lib/src/CSpellConfigFileReaderWriter.test.ts, packages/cspell-config-lib/src/CSpellConfigFileReaderWriter.ts, packages/cspell-lib/api/api.d.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLoader.test.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLoader.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/configSearch.test.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/configSearch.ts, packages/cspell-lib/src/lib/Settings/DefaultSettings.ts, packages/cspell-lib/src/lib/Settings/constants.ts
There are times it is necessary to prevent loading JavaScript based configuration.
It is now possible to switch the config loader into untrusted mode. In this mode, the loader will not load JavaScript files outside of the CSpell configuration.
This is to support: [Workspace Trust Extension Guide | Visual Studio Code Extension API](https://code.visualstudio.com/api/extension-guides/workspace-trust)
=> feat: Add untrusted mode to the config loader

packages/cspell-tools/fixtures/build-exclude/cspell-tools.config.yaml, packages/cspell-tools/fixtures/build-exclude/src/exclude.txt, packages/cspell-tools/fixtures/build-exclude/src/words.txt, packages/cspell-tools/src/__snapshots__/build.test.ts.snap, packages/cspell-tools/src/build.test.ts, packages/cspell-tools/src/compiler/CompileOptions.ts, packages/cspell-tools/src/compiler/__snapshots__/compile.test.ts.snap, packages/cspell-tools/src/compiler/compile.test.ts, packages/cspell-tools/src/compiler/compile.ts, packages/cspell-tools/src/compiler/wordListParser.ts, packages/cspell-tools/src/config/config.ts, packages/cspell-tools/src/test/TestHelper.ts
When compiling a word list, support excluding words based upon another word list.
This helps reduce the size of a dictionary.
=> fix: cspell-tools - support excluding words

packages/cspell-eslint-plugin/assets/options.schema.json, packages/cspell-eslint-plugin/src/common/options.cts, packages/cspell-eslint-plugin/src/common/options.test.cts
=> feat: Add `langauge` option to cspell eslint plugin

packages/cspell/fixtures/features/cached/cspell.json, packages/cspell/src/app/application.test.ts, packages/cspell/src/app/util/cache/createCache.test.ts, packages/cspell/src/app/util/cache/createCache.ts, packages/cspell/src/app/util/cache/fileEntryCache.ts
fixes: #5246
- Defaults to the `universal` format instead of legacy.
- Path separators are converted to `/` before being stored.
=> feat: Support sharing cache between windows and linux

packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLoader.test.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLoader.ts, packages/cspell-lib/src/lib/spellCheckFile.test.ts, packages/cspell/src/app/__snapshots__/app.test.ts.snap
=> fix: Improve the Configuration Loader Error Message

packages/cspell/src/app/lint/lint.ts
Configuration errors would block the spell checker from running. Using the `--no-exit-code` option will report the issue, but not prevent it from running to completion.
Related to #5334
=> fix: `--no-exit-code` will allow running even if there are config errors

packages/Samples/package.json, packages/cspell-bundled-dicts/package.json, packages/cspell-code-snippets/package.json, packages/cspell-config-lib/package.json, packages/cspell-dictionary/package.json, packages/cspell-eslint-plugin/package.json, packages/cspell-gitignore/package.json, packages/cspell-glob/package.json, packages/cspell-grammar/package.json, packages/cspell-io/package.json, packages/cspell-json-reporter/package.json, packages/cspell-lib/package.json, packages/cspell-pipe/package.json, packages/cspell-resolver/package.json, packages/cspell-service-bus/package.json, packages/cspell-strong-weak-map/package.json, packages/cspell-tools/package.json, packages/cspell-trie-lib/package.json, packages/cspell-trie/package.json, packages/cspell-types/package.json, packages/cspell/package.json, packages/dynamic-import/package.json, packages/hunspell-reader/package.json, pnpm-lock.yaml, scripts/package.json, scripts/update-package-json.mjs
Make sure the `"repository"` field is correct in all the `package.json` files.
=> chore: Script to Update `package.json` files.

packages/cspell-lib/src/lib/__snapshots__/index.test.ts.snap, packages/cspell-types/src/__snapshots__/index.test.ts.snap, packages/cspell-types/src/defineConfig.test.ts, packages/cspell-types/src/defineConfig.ts, packages/cspell-types/src/index.ts
=> fix: Adding defineConfig() to cspell-types

packages/cspell-io/src/node/file/fetch.test.ts, packages/cspell-io/src/node/file/stat.test.ts
https://httpbingo.org
http://httpbin.org has been timing out lately.
It is no longer actively maintained. See: https://github.com/postmanlabs/httpbin/issues/
=> test: Use httpbingo instead of httpbin

.github/workflows/integration-test.yml
Writing a comment to a PR needs special permission. For now, just just skip it if it fails.
See: [mshick/add-pr-comment](https://github.com/mshick/add-pr-comment/tree/main#proxy-for-fork-based-prs)
=> chore: prevent the summary from failing the build

docs/configuration/index.md
Fix https://github.com/streetsidesoftware/cspell/issues/5579
> In the [Configuration](https://cspell.org/configuration/#cspelljson-sections) documentation, the link to the Dictionaries doesn't work.
=> docs: Fix link to Dictionaries

packages/cspell-glob/package.json, pnpm-lock.yaml
The behavior on Windows has changed. Until that is fixed, lock the version to `4.0.5`.
See: https://github.com/micromatch/micromatch/issues/256
=> fix: lock version of `micromatch`

packages/cspell-lib/api/api.d.ts, packages/cspell-lib/src/lib/Document/isBinaryDoc.test.ts, packages/cspell-lib/src/lib/Document/isBinaryDoc.ts, packages/cspell-lib/src/lib/LanguageIds.ts, packages/cspell-lib/src/lib/spellCheckFile.test.ts, packages/cspell-lib/src/lib/spellCheckFile.ts
fixes #5779
- add `.mp4` to the video list
- treat unknown file types that contain 0x00 as binary.
=> fix: Make sure binary files are not checked.

packages/cspell-eslint-plugin/README.md, packages/cspell-eslint-plugin/assets/options.schema.json, packages/cspell-eslint-plugin/cspell.config.yaml, packages/cspell-eslint-plugin/fixtures/import-support/cspell.config.yaml, packages/cspell-eslint-plugin/fixtures/import-support/cspell.test.json, packages/cspell-eslint-plugin/fixtures/import-support/sample.ts, packages/cspell-eslint-plugin/package.json, packages/cspell-eslint-plugin/src/common/options.cts, packages/cspell-eslint-plugin/src/plugin/cspell-eslint-plugin.cts, packages/cspell-eslint-plugin/src/plugin/defaultCheckOptions.cts, packages/cspell-eslint-plugin/src/test/import.test.mts, packages/cspell-eslint-plugin/src/worker/spellCheck.mts, packages/cspell-lib/api/api.d.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLoader.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/defaultConfigLoader.ts, packages/cspell-lib/src/lib/Settings/Controller/configLoader/index.ts, packages/cspell-lib/src/lib/Settings/index.ts, packages/cspell-lib/src/lib/textValidation/docValidator.ts, pnpm-lock.yaml, pnpm-workspace.yaml, test-fixtures/dictionaries/test-dictionary/index.js, test-fixtures/dictionaries/test-dictionary/package.json, test-fixtures/dictionaries/test-dictionary/words.txt
=> fix: resolve imports from ESLint plugin

packages/cspell-tools/cspell-tools.config.schema.json, packages/cspell-tools/src/compiler/CompileOptions.ts, packages/cspell-tools/src/compiler/__snapshots__/wordListCompiler.test.ts.snap, packages/cspell-tools/src/compiler/compile.ts, packages/cspell-tools/src/compiler/wordListCompiler.test.ts, packages/cspell-tools/src/compiler/wordListCompiler.ts, packages/cspell-tools/src/config/config.ts
CSpell dictionary can contain directives that changes how the file is parsed. This fix is to have the cspell-tool add them to the file header.
=> fix(cspell-tools): support adding directives

packages/cspell-json-reporter/src/__snapshots__/index.test.ts.snap, packages/cspell-json-reporter/src/index.test.ts, packages/cspell-json-reporter/src/index.ts, packages/cspell/bin.mjs, packages/cspell/src/app/__snapshots__/app.test.ts.snap, packages/cspell/src/app/app.test.ts, packages/cspell/src/app/application.ts, packages/cspell/src/app/cli-reporter.test.ts, packages/cspell/src/app/cli-reporter.ts, packages/cspell/src/app/commandCheck.ts, packages/cspell/src/app/commandLink.ts, packages/cspell/src/app/commandTrace.ts, packages/cspell/src/app/console.ts, packages/cspell/src/app/emitters/suggestionsEmitter.ts, packages/cspell/src/app/emitters/traceEmitter.test.ts, packages/cspell/src/app/emitters/traceEmitter.ts, packages/cspell/src/app/featureFlags/featureFlags.test.ts, packages/cspell/src/app/featureFlags/featureFlags.ts, packages/cspell/src/app/index.ts, packages/cspell/src/app/lint/lint.ts, packages/cspell/src/app/models.ts, packages/cspell/src/app/util/cache/fileEntryCache.ts, test-packages/cspell/test-cspell-esm-reporter/src/reporter.ts
1. Do not use console.log/.error/.warn to display text.
2. Clean up the output so it doesn't use too much space.
=> fix: Use stdout and stderr to display text

packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryCollection.ts, packages/cspell-dictionary/src/SpellingDictionary/SpellingDictionaryFromTrie.ts, packages/cspell-dictionary/src/perf/has.perf.ts, packages/cspell-dictionary/src/perf/misc.perf.ts, packages/cspell-dictionary/src/util/AutoCache.ts, packages/cspell-trie-lib/api/api.d.ts, packages/cspell-trie-lib/src/lib/ITrie.ts, packages/cspell-trie-lib/src/lib/ITrieNode/FindOptions.ts, packages/cspell-trie-lib/src/lib/ITrieNode/ITrieNode.ts, packages/cspell-trie-lib/src/lib/ITrieNode/find.ts, packages/cspell-trie-lib/src/lib/TrieBlob/CharIndex.ts, packages/cspell-trie-lib/src/lib/TrieBlob/FastTrieBlob.ts, packages/cspell-trie-lib/src/lib/TrieBlob/FastTrieBlobIRoot.ts, packages/cspell-trie-lib/src/lib/TrieBlob/TrieBlob.ts, packages/cspell-trie-lib/src/lib/TrieBlob/TrieBlobIRoot.ts, packages/cspell-trie-lib/src/lib/TrieNode/trie.ts, packages/cspell-trie-lib/src/lib/buildITrie.ts, packages/cspell-trie-lib/src/perf/map.perf.ts
Start Metrics:
```
File: src/perf/has.perf.ts
Running Perf Suite: trie has
✔ trie has words             6.84 ops/sec      4 iterations  584.46ms time
✔ fastTrieBlob has words    13.16 ops/sec      7 iterations  531.93ms time
✔ trieBlob has words        16.89 ops/sec      9 iterations  532.98ms time
✔ iTrieFast has words       12.67 ops/sec      7 iterations  552.63ms time
✔ iTrieBlob has words       17.26 ops/sec      9 iterations  521.36ms time
done.
File: src/perf/has.perf.ts
Running Perf Suite: dictionary has
✔ dictionary has 100k words               14.98 ops/sec      8 iterations  533.90ms time
✔ dictionary has 100k words (2nd time)    15.85 ops/sec      9 iterations  567.87ms time
✔ collection has 100k words                4.98 ops/sec      3 iterations  602.34ms time
✔ iTrie has …
```
=> fix: speed up word look up.

package.json, packages/cspell-eslint-plugin/package.json, packages/cspell-io/package.json, pnpm-lock.yaml, website/package.json
The newest TypeScript is breaking Rollup
=> chore: lock TypeScript version

packages/flatpack-json/src/Flatpack.mts, packages/flatpack-json/src/Flatpack.test.mts
flatpack-json was caching the objects it got for performance. But this created an issue when one of those objects were updated in the background. Since the object was cached, it was assumed that nothing had changed.
=> fix: Remove object from cache

packages/cspell/package.json, packages/cspell/src/app/app.test.ts, packages/cspell/src/app/emitters/traceEmitter.test.ts, packages/cspell/src/app/util/pad.ts, packages/cspell/src/app/util/table.test.ts, pnpm-lock.yaml
This pull request replaces `strip-ansi` with native Node utilities [`util.stripVTControlCharacters`](https://nodejs.org/api/util.html#utilstripvtcontrolcharactersstr) added in Node 16.
The impact of this pull request is reducing the amount of unneeded dependencies.
=> chore(deps): replace strip-ansi with native Node API

packages/cspell-gitignore/src/helpers.ts, packages/hunspell-reader/.vscode/launch.json
=> fix: `.git` can be a file or a directory

packages/cspell-bundled-dicts/package.json, packages/cspell-config-lib/package.json, packages/cspell-dictionary/package.json, packages/cspell-eslint-plugin/package.json, packages/cspell-filetypes/package.json, packages/cspell-gitignore/package.json, packages/cspell-glob/package.json, packages/cspell-grammar/package.json, packages/cspell-io/package.json, packages/cspell-json-reporter/package.json, packages/cspell-lib/package.json, packages/cspell-normalize-json/package.json, packages/cspell-pipe/package.json, packages/cspell-resolver/package.json, packages/cspell-service-bus/package.json, packages/cspell-strong-weak-map/package.json, packages/cspell-tools/package.json, packages/cspell-trie-lib/package.json, packages/cspell-trie/package.json, packages/cspell-types/package.json, packages/cspell-url/package.json, packages/dynamic-import/package.json, packages/flatpack-json/package.json, packages/hunspell-reader/package.json, test-packages/dictionaries/companies/package.json, test-packages/dictionaries/software-terms/package.json
See: https://docs.npmjs.com/generating-provenance-statements
=> fix: Sign Published Packages

examples/dynamic-dictionaries/package.json, packages/cspell/package.json, pnpm-lock.yaml
fixes the issue mentioned here: https://github.com/streetsidesoftware/cspell/pull/6167#issuecomment-2415942929
=> chore: upgrade to tinyglobby 0.2.10

CONTRIBUTING.md, cspell.schema.json, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/CSpellSettingsDef.ts
The actual default is `universal`.
https://github.com/streetsidesoftware/cspell/blob/8053a7d10ce7820dc2d44dea47eb4b25964633af/packages/cspell/src/app/util/cache/createCache.ts#L57
=> docs: Have the schema / docs align with actual

packages/cspell-tools/src/compiler/wordListCompiler.test.ts, packages/cspell-tools/src/compiler/wordListCompiler.ts
This PR changes a single rule when merging compound forms:
When a word is allowed to be stand alone and a midfix compound, then allow it to be a prefix as well as a suffix.
The logic:
If we allow `code` and `strongcodetype`, then `codetype` or `strongcode` should also be allowed.
=> fix: cspell-tools - compounds

packages/cspell-lib/src/lib/textValidation/lineValidatorFactory.test.ts, packages/cspell-lib/src/lib/textValidation/lineValidatorFactory.ts
=> fix: catch flagged words with `-` when ending with `.`

packages/cspell-lib/src/lib/textValidation/lineValidatorFactory.ts
For some strange reason, the Hungarian dictionary ends up with a forbid on empty string. This would happen when matching against `".`.
=> fix: Make sure empty string is not checked.

packages/cspell-bundled-dicts/cspell-default.config.js, packages/cspell-bundled-dicts/cspell-default.config.ts, packages/cspell-bundled-dicts/package.json, pnpm-lock.yaml
It was already included by python, but now it is explicitly included.
=> fix: add data-science dictionary

.github/actions/setup-node/action.yaml, .github/actions/setup/action.yaml, .github/workflows/build-version-release.yml, .github/workflows/cspell-action.yml, .github/workflows/cspell-cli.yml, .github/workflows/deploy-website.yml, .github/workflows/reuseable-load-integrations-repo-list.yml, .github/workflows/update-dependabot.yml, .github/workflows/update-dependencies.yml, .github/workflows/update-dictionaries.yml, .github/workflows/update-integration-repositories.yml
Corepack seems to have been broken during the 4.2.0 roll out of setup-node. Rolling back to version 4.1.0 does not see to fix it.
The workaround is to force install corepack after node has been setup.
See: https://github.com/actions/setup-node/issues/1222
=> chore: Force setup-node to v4.1.0

docs/configuration/document-settings.md, website/docs/Configuration/document-settings.md
This adds examples for using spellchecker and spell-checker ignores. The PR tries to follow the same format as disables from the section above.
=> docs: add examples for spellchecker and spell-checker ignores

packages/cspell-eslint-plugin/fixtures/dictionaries/README.md, packages/cspell-eslint-plugin/fixtures/dictionaries/eslint.config.mjs, packages/cspell-eslint-plugin/fixtures/dictionaries/package.json, packages/cspell-eslint-plugin/fixtures/dictionaries/sample.js, packages/cspell-eslint-plugin/fixtures/import-support/package.json, packages/cspell-eslint-plugin/fixtures/issue-4870/eslint.config.mjs, packages/cspell-eslint-plugin/fixtures/json-support/eslint.config.mjs, packages/cspell-eslint-plugin/fixtures/json-support/package.json, packages/cspell-eslint-plugin/fixtures/mdx-support/package.json, packages/cspell-eslint-plugin/fixtures/yaml-support/eslint.config.mjs, packages/cspell-eslint-plugin/src/common/options.cts, packages/cspell-eslint-plugin/src/common/options.test.mts, packages/cspell-eslint-plugin/src/plugin/index.cts, packages/cspell-eslint-plugin/src/test/dictionary.test.mts, pnpm-lock.yaml, pnpm-workspace.yaml
Add helper methods:
- `defineCSpellPluginOptions`
- `defineCSpellConfig`
Add some examples for `supportNonStrictSearches`
=> fix: Add eslint plugin helpers

cspell.schema.json, packages/cspell-dictionary/src/SpellingDictionary/CachingDictionary.ts, packages/cspell-lib/api/api.d.ts, packages/cspell-lib/src/lib/__snapshots__/index.test.ts.snap, packages/cspell-lib/src/lib/textValidation/ValidationTypes.ts, packages/cspell-lib/src/lib/textValidation/lineValidatorFactory.ts, packages/cspell-lib/src/lib/textValidation/textValidator.test.ts, packages/cspell-types/cspell.schema.json, packages/cspell-types/src/CSpellSettingsDef.ts, packages/cspell-types/src/configFields.ts
Implement `unknownWords` config based on the following discussion: https://github.com/streetsidesoftware/cspell/discussions/5751.
- `report` - the default
- `ignore` - ignore most unknown words except ones with simple fixes (must have a preferred fix).
- `ignore-all` - ignore all unknown words.
I'm mostly interested in the `ignore` option, where I want `cspell` to error only for common English words with a simple fix (e.g., `necesary` -> `necessary`), which will allow us to adopt `cspell` without having to deal with a custom dictionary.
Feel free to take over this pull request. I'm unfamiliar with this repository, but I wanted to try a proof of concept to see if it would work for our app—It did!
=> feat: implement `unknownWords` config (part 1)

package.json, pnpm-lock.yaml
=> chore: lock vitest

packages/cspell/src/app/__snapshots__/app.test.ts.snap, packages/cspell/src/app/app.mts, packages/cspell/src/app/app.test.ts, packages/cspell/src/app/application.mts, packages/cspell/src/app/commandDictionaries.ts, packages/cspell/src/app/emitters/dictionaryListEmitter.ts, packages/cspell/src/app/emitters/helpers.test.ts, packages/cspell/src/app/emitters/helpers.ts, packages/cspell/src/app/emitters/traceEmitter.test.ts, packages/cspell/src/app/emitters/traceEmitter.ts, packages/cspell/src/app/options.ts
Add new `dictionaries` command to the cli
```
Usage: cspell dictionaries [options]
List dictionaries
Options:
-c, --config <cspell.json>  Configuration file to use.  By default cspell
looks for cspell.json in the current directory.
--path-format <format>      Configure how to display the dictionary path.
(choices: "hide", "short", "long", "full",
default: Display most of the path.)
--color                     Force color.
--no-color                  Turn off color.
--no-default-configuration  Do not load the default configuration and
dictionaries.
-h, --help                  display help for command
```
=> feat: Add command `dictionaries`

packages/cspell/src/util/reporters.ts, packages/cspell/tools/patch-version.mjs
Fix the logic to show an issue when the reporting level is set to `simple`. The code worked because of the assumption that  `hasSimpleSuggestions` would be true if `hasPreferredSuggestions` was true.
=> fix: show simple typos reporting

packages/cspell/package.json, packages/cspell/src/util/cache/DiskCache.test.ts, packages/cspell/src/util/cache/file-entry-cache.mts, packages/cspell/src/util/cache/file-entry-cache/index.ts, packages/cspell/src/util/cache/fileEntryCache.ts, packages/cspell/vitest.config.mjs, pnpm-lock.yaml
Deprecating the use of file-entry-cache.
v10 of `file-entry-cache` breaks the spell checker and bloats the cache size.
This PR is the first step in reducing the dependency upon file-entry-cache and its dependencies.
=> fix: Replace file-entry-cache
